'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace KBMSAPI
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SimpleApiResponse", [Namespace]:="http://kingpower.com/kbms/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SimpleApiResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private SuccessField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DataField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorCodeField As String
        
        Private RecordCountField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Success() As Boolean
            Get
                Return Me.SuccessField
            End Get
            Set
                If (Me.SuccessField.Equals(value) <> true) Then
                    Me.SuccessField = value
                    Me.RaisePropertyChanged("Success")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Data() As String
            Get
                Return Me.DataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DataField, value) <> true) Then
                    Me.DataField = value
                    Me.RaisePropertyChanged("Data")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property ErrorCode() As String
            Get
                Return Me.ErrorCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorCodeField, value) <> true) Then
                    Me.ErrorCodeField = value
                    Me.RaisePropertyChanged("ErrorCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property RecordCount() As Integer
            Get
                Return Me.RecordCountField
            End Get
            Set
                If (Me.RecordCountField.Equals(value) <> true) Then
                    Me.RecordCountField = value
                    Me.RaisePropertyChanged("RecordCount")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://kingpower.com/kbms/", ConfigurationName:="KBMSAPI.KBMSApiSoap")>  _
    Public Interface KBMSApiSoap
        
        'CODEGEN: Generating message contract since element name modifiedDate from namespace http://kingpower.com/kbms/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/GetPO", ReplyAction:="*")>  _
        Function GetPO(ByVal request As KBMSAPI.GetPORequest) As KBMSAPI.GetPOResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/GetPO", ReplyAction:="*")>  _
        Function GetPOAsync(ByVal request As KBMSAPI.GetPORequest) As System.Threading.Tasks.Task(Of KBMSAPI.GetPOResponse)
        
        'CODEGEN: Generating message contract since element name planDataJson from namespace http://kingpower.com/kbms/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/UploadOTBPlan", ReplyAction:="*")>  _
        Function UploadOTBPlan(ByVal request As KBMSAPI.UploadOTBPlanRequest) As KBMSAPI.UploadOTBPlanResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/UploadOTBPlan", ReplyAction:="*")>  _
        Function UploadOTBPlanAsync(ByVal request As KBMSAPI.UploadOTBPlanRequest) As System.Threading.Tasks.Task(Of KBMSAPI.UploadOTBPlanResponse)
        
        'CODEGEN: Generating message contract since element name switchRequestJson from namespace http://kingpower.com/kbms/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/UpdateOTBPlan", ReplyAction:="*")>  _
        Function UpdateOTBPlan(ByVal request As KBMSAPI.UpdateOTBPlanRequest) As KBMSAPI.UpdateOTBPlanResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/UpdateOTBPlan", ReplyAction:="*")>  _
        Function UpdateOTBPlanAsync(ByVal request As KBMSAPI.UpdateOTBPlanRequest) As System.Threading.Tasks.Task(Of KBMSAPI.UpdateOTBPlanResponse)
        
        'CODEGEN: Generating message contract since element name GetPOSimpleResult from namespace http://kingpower.com/kbms/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/GetPOSimple", ReplyAction:="*")>  _
        Function GetPOSimple(ByVal request As KBMSAPI.GetPOSimpleRequest) As KBMSAPI.GetPOSimpleResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/GetPOSimple", ReplyAction:="*")>  _
        Function GetPOSimpleAsync(ByVal request As KBMSAPI.GetPOSimpleRequest) As System.Threading.Tasks.Task(Of KBMSAPI.GetPOSimpleResponse)
        
        'CODEGEN: Generating message contract since element name modifiedDate from namespace http://kingpower.com/kbms/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/GetPOByDate", ReplyAction:="*")>  _
        Function GetPOByDate(ByVal request As KBMSAPI.GetPOByDateRequest) As KBMSAPI.GetPOByDateResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/GetPOByDate", ReplyAction:="*")>  _
        Function GetPOByDateAsync(ByVal request As KBMSAPI.GetPOByDateRequest) As System.Threading.Tasks.Task(Of KBMSAPI.GetPOByDateResponse)
        
        'CODEGEN: Generating message contract since element name HealthCheckResult from namespace http://kingpower.com/kbms/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/HealthCheck", ReplyAction:="*")>  _
        Function HealthCheck(ByVal request As KBMSAPI.HealthCheckRequest) As KBMSAPI.HealthCheckResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/HealthCheck", ReplyAction:="*")>  _
        Function HealthCheckAsync(ByVal request As KBMSAPI.HealthCheckRequest) As System.Threading.Tasks.Task(Of KBMSAPI.HealthCheckResponse)
        
        'CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://kingpower.com/kbms/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As KBMSAPI.HelloWorldRequest) As KBMSAPI.HelloWorldResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync(ByVal request As KBMSAPI.HelloWorldRequest) As System.Threading.Tasks.Task(Of KBMSAPI.HelloWorldResponse)
        
        'CODEGEN: Generating message contract since element name TestNoAuthResult from namespace http://kingpower.com/kbms/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/TestNoAuth", ReplyAction:="*")>  _
        Function TestNoAuth(ByVal request As KBMSAPI.TestNoAuthRequest) As KBMSAPI.TestNoAuthResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/TestNoAuth", ReplyAction:="*")>  _
        Function TestNoAuthAsync(ByVal request As KBMSAPI.TestNoAuthRequest) As System.Threading.Tasks.Task(Of KBMSAPI.TestNoAuthResponse)
        
        'CODEGEN: Generating message contract since element name TestSAPConnectionResult from namespace http://kingpower.com/kbms/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/TestSAPConnection", ReplyAction:="*")>  _
        Function TestSAPConnection(ByVal request As KBMSAPI.TestSAPConnectionRequest) As KBMSAPI.TestSAPConnectionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/TestSAPConnection", ReplyAction:="*")>  _
        Function TestSAPConnectionAsync(ByVal request As KBMSAPI.TestSAPConnectionRequest) As System.Threading.Tasks.Task(Of KBMSAPI.TestSAPConnectionResponse)
        
        'CODEGEN: Generating message contract since element name GetApiInfoResult from namespace http://kingpower.com/kbms/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/GetApiInfo", ReplyAction:="*")>  _
        Function GetApiInfo(ByVal request As KBMSAPI.GetApiInfoRequest) As KBMSAPI.GetApiInfoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://kingpower.com/kbms/GetApiInfo", ReplyAction:="*")>  _
        Function GetApiInfoAsync(ByVal request As KBMSAPI.GetApiInfoRequest) As System.Threading.Tasks.Task(Of KBMSAPI.GetApiInfoResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPORequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPO", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.GetPORequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.GetPORequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class GetPORequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public modifiedDate As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public top As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public skip As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public orderby As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal modifiedDate As String, ByVal top As Integer, ByVal skip As Integer, ByVal orderby As String)
            MyBase.New
            Me.modifiedDate = modifiedDate
            Me.top = top
            Me.skip = skip
            Me.orderby = orderby
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPOResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPOResponse", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.GetPOResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.GetPOResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class GetPOResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetPOResult As KBMSAPI.SimpleApiResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetPOResult As KBMSAPI.SimpleApiResponse)
            MyBase.New
            Me.GetPOResult = GetPOResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UploadOTBPlanRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UploadOTBPlan", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.UploadOTBPlanRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.UploadOTBPlanRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class UploadOTBPlanRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public planDataJson As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal planDataJson As String)
            MyBase.New
            Me.planDataJson = planDataJson
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UploadOTBPlanResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UploadOTBPlanResponse", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.UploadOTBPlanResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.UploadOTBPlanResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class UploadOTBPlanResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UploadOTBPlanResult As KBMSAPI.SimpleApiResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UploadOTBPlanResult As KBMSAPI.SimpleApiResponse)
            MyBase.New
            Me.UploadOTBPlanResult = UploadOTBPlanResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateOTBPlanRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateOTBPlan", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.UpdateOTBPlanRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.UpdateOTBPlanRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class UpdateOTBPlanRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public switchRequestJson As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal switchRequestJson As String)
            MyBase.New
            Me.switchRequestJson = switchRequestJson
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateOTBPlanResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateOTBPlanResponse", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.UpdateOTBPlanResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.UpdateOTBPlanResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class UpdateOTBPlanResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UpdateOTBPlanResult As KBMSAPI.SimpleApiResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UpdateOTBPlanResult As KBMSAPI.SimpleApiResponse)
            MyBase.New
            Me.UpdateOTBPlanResult = UpdateOTBPlanResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPOSimpleRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPOSimple", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.GetPOSimpleRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.GetPOSimpleRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetPOSimpleRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPOSimpleResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPOSimpleResponse", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.GetPOSimpleResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.GetPOSimpleResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class GetPOSimpleResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetPOSimpleResult As KBMSAPI.SimpleApiResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetPOSimpleResult As KBMSAPI.SimpleApiResponse)
            MyBase.New
            Me.GetPOSimpleResult = GetPOSimpleResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPOByDateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPOByDate", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.GetPOByDateRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.GetPOByDateRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class GetPOByDateRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public modifiedDate As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal modifiedDate As String)
            MyBase.New
            Me.modifiedDate = modifiedDate
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPOByDateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPOByDateResponse", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.GetPOByDateResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.GetPOByDateResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class GetPOByDateResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetPOByDateResult As KBMSAPI.SimpleApiResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetPOByDateResult As KBMSAPI.SimpleApiResponse)
            MyBase.New
            Me.GetPOByDateResult = GetPOByDateResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HealthCheckRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HealthCheck", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.HealthCheckRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.HealthCheckRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HealthCheckRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HealthCheckResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HealthCheckResponse", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.HealthCheckResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.HealthCheckResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class HealthCheckResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HealthCheckResult As KBMSAPI.SimpleApiResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HealthCheckResult As KBMSAPI.SimpleApiResponse)
            MyBase.New
            Me.HealthCheckResult = HealthCheckResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TestNoAuthRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TestNoAuth", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.TestNoAuthRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.TestNoAuthRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class TestNoAuthRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TestNoAuthResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TestNoAuthResponse", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.TestNoAuthResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.TestNoAuthResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class TestNoAuthResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public TestNoAuthResult As KBMSAPI.SimpleApiResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TestNoAuthResult As KBMSAPI.SimpleApiResponse)
            MyBase.New
            Me.TestNoAuthResult = TestNoAuthResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TestSAPConnectionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TestSAPConnection", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.TestSAPConnectionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.TestSAPConnectionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class TestSAPConnectionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TestSAPConnectionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TestSAPConnectionResponse", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.TestSAPConnectionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.TestSAPConnectionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class TestSAPConnectionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public TestSAPConnectionResult As KBMSAPI.SimpleApiResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TestSAPConnectionResult As KBMSAPI.SimpleApiResponse)
            MyBase.New
            Me.TestSAPConnectionResult = TestSAPConnectionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetApiInfoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetApiInfo", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.GetApiInfoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.GetApiInfoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetApiInfoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetApiInfoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetApiInfoResponse", [Namespace]:="http://kingpower.com/kbms/", Order:=0)>  _
        Public Body As KBMSAPI.GetApiInfoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KBMSAPI.GetApiInfoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://kingpower.com/kbms/")>  _
    Partial Public Class GetApiInfoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetApiInfoResult As KBMSAPI.SimpleApiResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetApiInfoResult As KBMSAPI.SimpleApiResponse)
            MyBase.New
            Me.GetApiInfoResult = GetApiInfoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface KBMSApiSoapChannel
        Inherits KBMSAPI.KBMSApiSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class KBMSApiSoapClient
        Inherits System.ServiceModel.ClientBase(Of KBMSAPI.KBMSApiSoap)
        Implements KBMSAPI.KBMSApiSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_GetPO(ByVal request As KBMSAPI.GetPORequest) As KBMSAPI.GetPOResponse Implements KBMSAPI.KBMSApiSoap.GetPO
            Return MyBase.Channel.GetPO(request)
        End Function
        
        Public Function GetPO(ByVal modifiedDate As String, ByVal top As Integer, ByVal skip As Integer, ByVal orderby As String) As KBMSAPI.SimpleApiResponse
            Dim inValue As KBMSAPI.GetPORequest = New KBMSAPI.GetPORequest()
            inValue.Body = New KBMSAPI.GetPORequestBody()
            inValue.Body.modifiedDate = modifiedDate
            inValue.Body.top = top
            inValue.Body.skip = skip
            inValue.Body.orderby = orderby
            Dim retVal As KBMSAPI.GetPOResponse = CType(Me,KBMSAPI.KBMSApiSoap).GetPO(inValue)
            Return retVal.Body.GetPOResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_GetPOAsync(ByVal request As KBMSAPI.GetPORequest) As System.Threading.Tasks.Task(Of KBMSAPI.GetPOResponse) Implements KBMSAPI.KBMSApiSoap.GetPOAsync
            Return MyBase.Channel.GetPOAsync(request)
        End Function
        
        Public Function GetPOAsync(ByVal modifiedDate As String, ByVal top As Integer, ByVal skip As Integer, ByVal orderby As String) As System.Threading.Tasks.Task(Of KBMSAPI.GetPOResponse)
            Dim inValue As KBMSAPI.GetPORequest = New KBMSAPI.GetPORequest()
            inValue.Body = New KBMSAPI.GetPORequestBody()
            inValue.Body.modifiedDate = modifiedDate
            inValue.Body.top = top
            inValue.Body.skip = skip
            inValue.Body.orderby = orderby
            Return CType(Me,KBMSAPI.KBMSApiSoap).GetPOAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_UploadOTBPlan(ByVal request As KBMSAPI.UploadOTBPlanRequest) As KBMSAPI.UploadOTBPlanResponse Implements KBMSAPI.KBMSApiSoap.UploadOTBPlan
            Return MyBase.Channel.UploadOTBPlan(request)
        End Function
        
        Public Function UploadOTBPlan(ByVal planDataJson As String) As KBMSAPI.SimpleApiResponse
            Dim inValue As KBMSAPI.UploadOTBPlanRequest = New KBMSAPI.UploadOTBPlanRequest()
            inValue.Body = New KBMSAPI.UploadOTBPlanRequestBody()
            inValue.Body.planDataJson = planDataJson
            Dim retVal As KBMSAPI.UploadOTBPlanResponse = CType(Me,KBMSAPI.KBMSApiSoap).UploadOTBPlan(inValue)
            Return retVal.Body.UploadOTBPlanResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_UploadOTBPlanAsync(ByVal request As KBMSAPI.UploadOTBPlanRequest) As System.Threading.Tasks.Task(Of KBMSAPI.UploadOTBPlanResponse) Implements KBMSAPI.KBMSApiSoap.UploadOTBPlanAsync
            Return MyBase.Channel.UploadOTBPlanAsync(request)
        End Function
        
        Public Function UploadOTBPlanAsync(ByVal planDataJson As String) As System.Threading.Tasks.Task(Of KBMSAPI.UploadOTBPlanResponse)
            Dim inValue As KBMSAPI.UploadOTBPlanRequest = New KBMSAPI.UploadOTBPlanRequest()
            inValue.Body = New KBMSAPI.UploadOTBPlanRequestBody()
            inValue.Body.planDataJson = planDataJson
            Return CType(Me,KBMSAPI.KBMSApiSoap).UploadOTBPlanAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_UpdateOTBPlan(ByVal request As KBMSAPI.UpdateOTBPlanRequest) As KBMSAPI.UpdateOTBPlanResponse Implements KBMSAPI.KBMSApiSoap.UpdateOTBPlan
            Return MyBase.Channel.UpdateOTBPlan(request)
        End Function
        
        Public Function UpdateOTBPlan(ByVal switchRequestJson As String) As KBMSAPI.SimpleApiResponse
            Dim inValue As KBMSAPI.UpdateOTBPlanRequest = New KBMSAPI.UpdateOTBPlanRequest()
            inValue.Body = New KBMSAPI.UpdateOTBPlanRequestBody()
            inValue.Body.switchRequestJson = switchRequestJson
            Dim retVal As KBMSAPI.UpdateOTBPlanResponse = CType(Me,KBMSAPI.KBMSApiSoap).UpdateOTBPlan(inValue)
            Return retVal.Body.UpdateOTBPlanResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_UpdateOTBPlanAsync(ByVal request As KBMSAPI.UpdateOTBPlanRequest) As System.Threading.Tasks.Task(Of KBMSAPI.UpdateOTBPlanResponse) Implements KBMSAPI.KBMSApiSoap.UpdateOTBPlanAsync
            Return MyBase.Channel.UpdateOTBPlanAsync(request)
        End Function
        
        Public Function UpdateOTBPlanAsync(ByVal switchRequestJson As String) As System.Threading.Tasks.Task(Of KBMSAPI.UpdateOTBPlanResponse)
            Dim inValue As KBMSAPI.UpdateOTBPlanRequest = New KBMSAPI.UpdateOTBPlanRequest()
            inValue.Body = New KBMSAPI.UpdateOTBPlanRequestBody()
            inValue.Body.switchRequestJson = switchRequestJson
            Return CType(Me,KBMSAPI.KBMSApiSoap).UpdateOTBPlanAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_GetPOSimple(ByVal request As KBMSAPI.GetPOSimpleRequest) As KBMSAPI.GetPOSimpleResponse Implements KBMSAPI.KBMSApiSoap.GetPOSimple
            Return MyBase.Channel.GetPOSimple(request)
        End Function
        
        Public Function GetPOSimple() As KBMSAPI.SimpleApiResponse
            Dim inValue As KBMSAPI.GetPOSimpleRequest = New KBMSAPI.GetPOSimpleRequest()
            inValue.Body = New KBMSAPI.GetPOSimpleRequestBody()
            Dim retVal As KBMSAPI.GetPOSimpleResponse = CType(Me,KBMSAPI.KBMSApiSoap).GetPOSimple(inValue)
            Return retVal.Body.GetPOSimpleResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_GetPOSimpleAsync(ByVal request As KBMSAPI.GetPOSimpleRequest) As System.Threading.Tasks.Task(Of KBMSAPI.GetPOSimpleResponse) Implements KBMSAPI.KBMSApiSoap.GetPOSimpleAsync
            Return MyBase.Channel.GetPOSimpleAsync(request)
        End Function
        
        Public Function GetPOSimpleAsync() As System.Threading.Tasks.Task(Of KBMSAPI.GetPOSimpleResponse)
            Dim inValue As KBMSAPI.GetPOSimpleRequest = New KBMSAPI.GetPOSimpleRequest()
            inValue.Body = New KBMSAPI.GetPOSimpleRequestBody()
            Return CType(Me,KBMSAPI.KBMSApiSoap).GetPOSimpleAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_GetPOByDate(ByVal request As KBMSAPI.GetPOByDateRequest) As KBMSAPI.GetPOByDateResponse Implements KBMSAPI.KBMSApiSoap.GetPOByDate
            Return MyBase.Channel.GetPOByDate(request)
        End Function
        
        Public Function GetPOByDate(ByVal modifiedDate As String) As KBMSAPI.SimpleApiResponse
            Dim inValue As KBMSAPI.GetPOByDateRequest = New KBMSAPI.GetPOByDateRequest()
            inValue.Body = New KBMSAPI.GetPOByDateRequestBody()
            inValue.Body.modifiedDate = modifiedDate
            Dim retVal As KBMSAPI.GetPOByDateResponse = CType(Me,KBMSAPI.KBMSApiSoap).GetPOByDate(inValue)
            Return retVal.Body.GetPOByDateResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_GetPOByDateAsync(ByVal request As KBMSAPI.GetPOByDateRequest) As System.Threading.Tasks.Task(Of KBMSAPI.GetPOByDateResponse) Implements KBMSAPI.KBMSApiSoap.GetPOByDateAsync
            Return MyBase.Channel.GetPOByDateAsync(request)
        End Function
        
        Public Function GetPOByDateAsync(ByVal modifiedDate As String) As System.Threading.Tasks.Task(Of KBMSAPI.GetPOByDateResponse)
            Dim inValue As KBMSAPI.GetPOByDateRequest = New KBMSAPI.GetPOByDateRequest()
            inValue.Body = New KBMSAPI.GetPOByDateRequestBody()
            inValue.Body.modifiedDate = modifiedDate
            Return CType(Me,KBMSAPI.KBMSApiSoap).GetPOByDateAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_HealthCheck(ByVal request As KBMSAPI.HealthCheckRequest) As KBMSAPI.HealthCheckResponse Implements KBMSAPI.KBMSApiSoap.HealthCheck
            Return MyBase.Channel.HealthCheck(request)
        End Function
        
        Public Function HealthCheck() As KBMSAPI.SimpleApiResponse
            Dim inValue As KBMSAPI.HealthCheckRequest = New KBMSAPI.HealthCheckRequest()
            inValue.Body = New KBMSAPI.HealthCheckRequestBody()
            Dim retVal As KBMSAPI.HealthCheckResponse = CType(Me,KBMSAPI.KBMSApiSoap).HealthCheck(inValue)
            Return retVal.Body.HealthCheckResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_HealthCheckAsync(ByVal request As KBMSAPI.HealthCheckRequest) As System.Threading.Tasks.Task(Of KBMSAPI.HealthCheckResponse) Implements KBMSAPI.KBMSApiSoap.HealthCheckAsync
            Return MyBase.Channel.HealthCheckAsync(request)
        End Function
        
        Public Function HealthCheckAsync() As System.Threading.Tasks.Task(Of KBMSAPI.HealthCheckResponse)
            Dim inValue As KBMSAPI.HealthCheckRequest = New KBMSAPI.HealthCheckRequest()
            inValue.Body = New KBMSAPI.HealthCheckRequestBody()
            Return CType(Me,KBMSAPI.KBMSApiSoap).HealthCheckAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_HelloWorld(ByVal request As KBMSAPI.HelloWorldRequest) As KBMSAPI.HelloWorldResponse Implements KBMSAPI.KBMSApiSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As KBMSAPI.HelloWorldRequest = New KBMSAPI.HelloWorldRequest()
            inValue.Body = New KBMSAPI.HelloWorldRequestBody()
            Dim retVal As KBMSAPI.HelloWorldResponse = CType(Me,KBMSAPI.KBMSApiSoap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_HelloWorldAsync(ByVal request As KBMSAPI.HelloWorldRequest) As System.Threading.Tasks.Task(Of KBMSAPI.HelloWorldResponse) Implements KBMSAPI.KBMSApiSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(request)
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of KBMSAPI.HelloWorldResponse)
            Dim inValue As KBMSAPI.HelloWorldRequest = New KBMSAPI.HelloWorldRequest()
            inValue.Body = New KBMSAPI.HelloWorldRequestBody()
            Return CType(Me,KBMSAPI.KBMSApiSoap).HelloWorldAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_TestNoAuth(ByVal request As KBMSAPI.TestNoAuthRequest) As KBMSAPI.TestNoAuthResponse Implements KBMSAPI.KBMSApiSoap.TestNoAuth
            Return MyBase.Channel.TestNoAuth(request)
        End Function
        
        Public Function TestNoAuth() As KBMSAPI.SimpleApiResponse
            Dim inValue As KBMSAPI.TestNoAuthRequest = New KBMSAPI.TestNoAuthRequest()
            inValue.Body = New KBMSAPI.TestNoAuthRequestBody()
            Dim retVal As KBMSAPI.TestNoAuthResponse = CType(Me,KBMSAPI.KBMSApiSoap).TestNoAuth(inValue)
            Return retVal.Body.TestNoAuthResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_TestNoAuthAsync(ByVal request As KBMSAPI.TestNoAuthRequest) As System.Threading.Tasks.Task(Of KBMSAPI.TestNoAuthResponse) Implements KBMSAPI.KBMSApiSoap.TestNoAuthAsync
            Return MyBase.Channel.TestNoAuthAsync(request)
        End Function
        
        Public Function TestNoAuthAsync() As System.Threading.Tasks.Task(Of KBMSAPI.TestNoAuthResponse)
            Dim inValue As KBMSAPI.TestNoAuthRequest = New KBMSAPI.TestNoAuthRequest()
            inValue.Body = New KBMSAPI.TestNoAuthRequestBody()
            Return CType(Me,KBMSAPI.KBMSApiSoap).TestNoAuthAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_TestSAPConnection(ByVal request As KBMSAPI.TestSAPConnectionRequest) As KBMSAPI.TestSAPConnectionResponse Implements KBMSAPI.KBMSApiSoap.TestSAPConnection
            Return MyBase.Channel.TestSAPConnection(request)
        End Function
        
        Public Function TestSAPConnection() As KBMSAPI.SimpleApiResponse
            Dim inValue As KBMSAPI.TestSAPConnectionRequest = New KBMSAPI.TestSAPConnectionRequest()
            inValue.Body = New KBMSAPI.TestSAPConnectionRequestBody()
            Dim retVal As KBMSAPI.TestSAPConnectionResponse = CType(Me,KBMSAPI.KBMSApiSoap).TestSAPConnection(inValue)
            Return retVal.Body.TestSAPConnectionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_TestSAPConnectionAsync(ByVal request As KBMSAPI.TestSAPConnectionRequest) As System.Threading.Tasks.Task(Of KBMSAPI.TestSAPConnectionResponse) Implements KBMSAPI.KBMSApiSoap.TestSAPConnectionAsync
            Return MyBase.Channel.TestSAPConnectionAsync(request)
        End Function
        
        Public Function TestSAPConnectionAsync() As System.Threading.Tasks.Task(Of KBMSAPI.TestSAPConnectionResponse)
            Dim inValue As KBMSAPI.TestSAPConnectionRequest = New KBMSAPI.TestSAPConnectionRequest()
            inValue.Body = New KBMSAPI.TestSAPConnectionRequestBody()
            Return CType(Me,KBMSAPI.KBMSApiSoap).TestSAPConnectionAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_GetApiInfo(ByVal request As KBMSAPI.GetApiInfoRequest) As KBMSAPI.GetApiInfoResponse Implements KBMSAPI.KBMSApiSoap.GetApiInfo
            Return MyBase.Channel.GetApiInfo(request)
        End Function
        
        Public Function GetApiInfo() As KBMSAPI.SimpleApiResponse
            Dim inValue As KBMSAPI.GetApiInfoRequest = New KBMSAPI.GetApiInfoRequest()
            inValue.Body = New KBMSAPI.GetApiInfoRequestBody()
            Dim retVal As KBMSAPI.GetApiInfoResponse = CType(Me,KBMSAPI.KBMSApiSoap).GetApiInfo(inValue)
            Return retVal.Body.GetApiInfoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KBMSAPI_KBMSApiSoap_GetApiInfoAsync(ByVal request As KBMSAPI.GetApiInfoRequest) As System.Threading.Tasks.Task(Of KBMSAPI.GetApiInfoResponse) Implements KBMSAPI.KBMSApiSoap.GetApiInfoAsync
            Return MyBase.Channel.GetApiInfoAsync(request)
        End Function
        
        Public Function GetApiInfoAsync() As System.Threading.Tasks.Task(Of KBMSAPI.GetApiInfoResponse)
            Dim inValue As KBMSAPI.GetApiInfoRequest = New KBMSAPI.GetApiInfoRequest()
            inValue.Body = New KBMSAPI.GetApiInfoRequestBody()
            Return CType(Me,KBMSAPI.KBMSApiSoap).GetApiInfoAsync(inValue)
        End Function
    End Class
End Namespace
