USE [BMS];
GO

SET NOCOUNT ON;
GO

/* Generated from provided Excel files using openpyxl */

MERGE dbo.MS_Month AS T
USING
(
    VALUES
        (1, N'Jan'),
        (2, N'Feb'),
        (3, N'Mar'),
        (4, N'Apr'),
        (5, N'May'),
        (6, N'Jun'),
        (7, N'Jul'),
        (8, N'Aug'),
        (9, N'Sep'),
        (10, N'Oct'),
        (11, N'Nov'),
        (12, N'Dec')
) AS S (month_code, month_name_sh)
ON T.month_code = S.month_code
WHEN MATCHED THEN
    UPDATE SET
        T.month_name_sh = S.month_name_sh
WHEN NOT MATCHED BY TARGET THEN
    INSERT (month_code, month_name_sh)
    VALUES (S.month_code, S.month_name_sh);
GO

MERGE dbo.MS_Year AS T
USING
(
    VALUES
        (2026),
        (2027),
        (2028)
) AS S (Year_Kept)
ON T.Year_Kept = S.Year_Kept
WHEN NOT MATCHED BY TARGET THEN
    INSERT (Year_Kept)
    VALUES (S.Year_Kept);
GO

MERGE dbo.MS_CCY AS T
USING
(
    VALUES
        (N'THB', N'THB', 1),
        (N'EUR', N'EUR', 1),
        (N'USD', N'USD', 1),
        (N'HKD', N'HKD', 1),
        (N'SGD', N'SGD', 1),
        (N'AUD', N'AUD', 1),
        (N'CAD', N'CAD', 1),
        (N'JPY', N'JPY', 1),
        (N'GBP', N'GBP', 1),
        (N'CHF', N'CHF', 1)
) AS S (CCY_Code, CCY_Name, isActive)
ON T.CCY_Code = S.CCY_Code
WHEN MATCHED THEN
    UPDATE SET
        T.CCY_Name = S.CCY_Name, T.isActive = S.isActive
WHEN NOT MATCHED BY TARGET THEN
    INSERT (CCY_Code, CCY_Name, isActive)
    VALUES (S.CCY_Code, S.CCY_Name, S.isActive);
GO

MERGE dbo.MS_Company AS T
USING
(
    VALUES
        (N'1000', N'Company 1000'),
        (N'2000', N'Company 2000'),
        (N'3000', N'Company 3000')
) AS S (CompanyCode, CompanyNameShort)
ON T.CompanyCode = S.CompanyCode
WHEN MATCHED THEN
    UPDATE SET
        T.CompanyNameShort = S.CompanyNameShort
WHEN NOT MATCHED BY TARGET THEN
    INSERT (CompanyCode, CompanyNameShort)
    VALUES (S.CompanyCode, S.CompanyNameShort);
GO

MERGE dbo.MS_Segment AS T
USING
(
    VALUES
        (N'201', N'T/T Normal Pay local', 1),
        (N'200', N'T/T Normal', 1),
        (N'100', N'L/C Normal', 1),
        (N'230', N'T/T Advance Payment', 1),
        (N'300', N'Local', 1),
        (N'232', N'T/T Duty Paid Advance', 1),
        (N'310', N'Advance Local', 1)
) AS S (SegmentCode, SegmentName, isActive)
ON T.SegmentCode = S.SegmentCode
WHEN MATCHED THEN
    UPDATE SET
        T.SegmentName = S.SegmentName, T.isActive = S.isActive
WHEN NOT MATCHED BY TARGET THEN
    INSERT (SegmentCode, SegmentName, isActive)
    VALUES (S.SegmentCode, S.SegmentName, S.isActive);
GO

MERGE dbo.MS_Category AS T
USING
(
    VALUES
        (N'201', N'Perfume', 1),
        (N'202', N'Cosmetic', 1),
        (N'211', N'Liquor', 1),
        (N'212', N'Wine & Champagne', 1),
        (N'213', N'Tobacco', 1),
        (N'221', N'FA Leather Goods', 1),
        (N'222', N'FA Shoes', 1),
        (N'223', N'FA Ready-To-Wear', 1),
        (N'224', N'FA Scarves', 1),
        (N'225', N'FA Ties', 1),
        (N'226', N'FA Costume Jewellery', 1),
        (N'227', N'FA Sunglasses', 1),
        (N'231', N'Watch', 1),
        (N'232', N'Pen & Lighter', 1),
        (N'234', N'Jewellery', 1),
        (N'241', N'Import Foods', 1),
        (N'251', N'Electronics', 1),
        (N'301', N'Local Perfume', 1),
        (N'302', N'Local Cosmetic', 1),
        (N'303', N'AROMATHERAPY', 1),
        (N'311', N'Local Liquor & Wine', 1),
        (N'312', N'Local Tobacco', 1),
        (N'321', N'Local FA Leather Goods', 1),
        (N'322', N'Local FA Ready To Wear', 1),
        (N'323', N'Sport', 1),
        (N'324', N'LOCAL SUNGLASSES', 1),
        (N'331', N'Local Watch', 1),
        (N'333', N'Local Gold & Jewellery', 1),
        (N'334', N'LOCAL JEWELLERY', 1),
        (N'341', N'Local Food', 1),
        (N'351', N'Local Electronics', 1),
        (N'361', N'Local Toy & Kids Accessories', 1),
        (N'371', N'Thai Craft & Souvenir', 1),
        (N'378', N'OTOP', 1),
        (N'381', N'Royal Project', 1),
        (N'384', N'Health & Wellness', 1),
        (N'389', N'Fast Moving Consumer Goods', 1),
        (N'392', N'HOME AND KITCHEN', 1),
        (N'402', N'Duty Paid Cosmetic', 1),
        (N'403', N'Duty Paid Aromatherapy', 1),
        (N'421', N'Duty Paid Leather Goods', 1),
        (N'422', N'Duty Paid Ready-To-Wear', 1),
        (N'423', N'Duty Paid Sunglasses', 1),
        (N'471', N'Duty Paid Souvenirs', 1)
) AS S (Cate, Category, isActive)
ON T.Cate = S.Cate
WHEN MATCHED THEN
    UPDATE SET
        T.Category = S.Category, T.isActive = S.isActive
WHEN NOT MATCHED BY TARGET THEN
    INSERT (Cate, Category, isActive)
    VALUES (S.Cate, S.Category, S.isActive);
GO

MERGE dbo.MS_Brand AS T
USING
(
    VALUES
        (N'3MM', N'3M', 1),
        (N'555', N'STATE EXPRESS 555', 1),
        (N'5PG', N'FIVE PAGODDAS', 1),
        (N'ABD', N'AUGUSTINUS BADER', 1),
        (N'ABE', N'ABERLOUR', 1),
        (N'ABF', N'ABERFELDY', 1),
        (N'ABI', N'ABSINTHE', 1),
        (N'ABL', N'AMBER LEAF', 1),
        (N'ABS', N'ABSOLUT', 1),
        (N'ACI', N'AMICELLI', 1),
        (N'ADB', N'ARDBEG', 1),
        (N'ADD', N'ADIDAS', 1),
        (N'ADE', N'ARDMORE', 1),
        (N'AEX', N'ARMANI EXCHANGE', 1),
        (N'AFT', N'AFTER', 1),
        (N'AGN', N'Argentina Wine', 1),
        (N'AIF', N'AIRFLY', 1),
        (N'AIM', N'AIMM''S SNACK', 1),
        (N'AKT', N'AKITA', 1),
        (N'AMB', N'AMBROSE WINES', 1),
        (N'AML', N'AMARULA', 1),
        (N'AMP', N'AMPHAN', 1),
        (N'AMQ', N'ALEXANDER MCQUEEN', 1),
        (N'AMT', N'AMARETTO', 1),
        (N'ANA', N'AIMM''S NATURAL', 1),
        (N'ANB', N'ANTONIO BANDERAS', 1),
        (N'ANS', N'ANNA SUI', 1),
        (N'ANZ', N'ANESSA', 1),
        (N'AOD', N'AROMDIN', 1),
        (N'APO', N'APEROL', 1),
        (N'APP', N'APPLE', 1),
        (N'AQM', N'AQUA MARIS', 1),
        (N'AQP', N'ACQUA DI PARMA', 1),
        (N'ARD', N'ELIZABETH ARDEN', 1),
        (N'ARM', N'ARAMIS', 1),
        (N'AUC', N'AUCHENTOSHAN', 1),
        (N'AUE', N'AULTMORE', 1),
        (N'AUS', N'AUSTRALIAN WINE', 1),
        (N'AUT', N'AMRUT', 1),
        (N'AVD', N'AVEDA', 1),
        (N'AVE', N'AVELINES', 1),
        (N'B&H', N'BENSON & HEDGES', 1),
        (N'B&O', N'BANG & OLUFSEN', 1),
        (N'BAI', N'BAILEYS', 1),
        (N'BAM', N'BALMAIN PARIS HAIR COUTURE', 1),
        (N'BBD', N'BALBLAIR', 1),
        (N'BBV', N'BANGKOK BEER', 1),
        (N'BCD', N'BACARDI', 1),
        (N'BCG', N'BALENCIAGA', 1),
        (N'BCH', N'BEER CHANG', 1),
        (N'BCN', N'BAAN CHANG', 1),
        (N'BDB', N'BUADAENG', 1),
        (N'BDE', N'BIODERMA', 1),
        (N'BEF', N'BENEFIT', 1),
        (N'BEH', N'BE FISH', 1),
        (N'BES', N'BEER SINGHA', 1),
        (N'BFT', N'BUFFALO TRACE', 1),
        (N'BGA', N'BELUGA', 1),
        (N'BGD', N'BURGUNDY', 1),
        (N'BGN', N'BELGIAN CHOCOLATES', 1),
        (N'BHV', N'BEEHIVE', 1),
        (N'BIF', N'BISCOFF', 1),
        (N'BIM', N'BAI MONE', 1),
        (N'BKL', N'BY KILIAN', 1),
        (N'BKM', N'BLACKMORES', 1),
        (N'BKN', N'BARK THINS', 1),
        (N'BLD', N'BLEND', 1),
        (N'BLP', N'BLANCPAIN', 1),
        (N'BLT', N'BALLANTINE''S', 1),
        (N'BND', N'BENEDICTINE', 1),
        (N'BNE', N'BANNER', 1),
        (N'BNH', N'BENRIACH', 1),
        (N'BNR', N'BELL & ROSS', 1),
        (N'BOA', N'BOTAN', 1),
        (N'BOB', N'BOBBI BROWN', 1),
        (N'BOG', N'BORDEAUX GRAND CRU', 1),
        (N'BOH', N'BOHEM', 1),
        (N'BOL', N'BOLON', 1),
        (N'BOM', N'BOMBAY SAPPHIRE', 1),
        (N'BOP', N'BORDEAUX PRESTIGE', 1),
        (N'BOR', N'BORDEAUX REGULAR', 1),
        (N'BOW', N'BOWMORE', 1),
        (N'BPN', N'BEPANTHEN', 1),
        (N'BPT', N'BANNPHUTHAI', 1),
        (N'BRD', N'BRUICHLADDICH', 1),
        (N'BRK', N'BROOKSIDE', 1),
        (N'BRL', N'BREITLING', 1),
        (N'BTA', N'BOTANIST', 1),
        (N'BTG', N'BOTTEGA', 1),
        (N'BTM', N'BIOTHERM', 1),
        (N'BTY', N'BOUNTY', 1),
        (N'BUI', N'BULLEIT', 1),
        (N'BUR', N'BURBERRY', 1),
        (N'BUT', N'BUTLERS', 1),
        (N'BVD', N'BELVEDERE', 1),
        (N'BVL', N'BVLGARI', 1),
        (N'BVN', N'BALVENIE', 1),
        (N'BVT', N'BOTTEGA VENETA', 1),
        (N'BYD', N'BYREDO', 1),
        (N'BYE', N'BYEBYE FEVER', 1),
        (N'CA1', N'Cleer Audio', 1),
        (N'CAM', N'CAMEL', 1),
        (N'CAO', N'CAOLILA', 1),
        (N'CAP', N'CAPTAIN MORGAN', 1),
        (N'CAR', N'CARTIER', 1),
        (N'CAS', N'CASIO', 1),
        (N'CBD', N'CHATELLE', 1),
        (N'CBY', N'CHALONGBAYRUM', 1),
        (N'CDG', N'CODIGO', 1),
        (N'CDI', N'CAPERDONICH', 1),
        (N'CDN', N'CHANDON', 1),
        (N'CEB', N'CELEBRATION', 1),
        (N'CEL', N'CELINE', 1),
        (N'CFN', N'CALIFORNIA', 1),
        (N'CFR', N'CRAFTER’S', 1),
        (N'CGF', N'CANADA GOOSE', 1),
        (N'CGN', N'CIGARONNE', 1),
        (N'CGR', N'CIGRAAL', 1),
        (N'CHL', N'CHLOE', 1),
        (N'CHN', N'CHANEL', 1),
        (N'CHR', N'CHIVAS REGAL', 1),
        (N'CHU', N'CHUNG HWA', 1),
        (N'CHY', N'CHOYA UME', 1),
        (N'CIE', N'CHILEAN WINE', 1),
        (N'CIJ', N'CINCORO', 1),
        (N'CIT', N'CITIZEN', 1),
        (N'CKE', N'COKE', 1),
        (N'CKL', N'CALVIN KLEIN', 1),
        (N'CKR', N'CHAISIKARIN', 1),
        (N'CLA', N'CLARINS', 1),
        (N'CLB', N'CLOUDY BAY', 1),
        (N'CLW', N'CLEW', 1),
        (N'CMF', N'CMF', 1),
        (N'CMU', N'CAMUS', 1),
        (N'CNI', N'CHANAI', 1),
        (N'CNQ', N'CLINIQUE', 1),
        (N'CNS', N'CANESTEN', 1),
        (N'COA', N'COACH', 1),
        (N'COC', N'COCKBURN''S', 1),
        (N'COI', N'COINTREAU', 1),
        (N'COP', N'COPPER DOG', 1),
        (N'COU', N'COURVOISIER', 1),
        (N'CPB', N'CLE DE PEAU BEAUTE', 1),
        (N'CPC', N'CHUPA CHUPS', 1),
        (N'CPD', N'CHOPARD', 1),
        (N'CPM', N'CAP LIMAU', 1),
        (N'CPR', N'CAMPARI', 1),
        (N'CRG', N'CAORUNN', 1),
        (N'CRL', N'CAROLINA HERRERA', 1),
        (N'CSB', N'CLASSIC BOOM', 1),
        (N'CSD', N'CHASADA HONGSUCHON', 1),
        (N'CT3', N'CHARLOTTE TILBURY', 1),
        (N'CTB', N'CHANTABRU', 1),
        (N'CTN', N'CHARTEE NOISOPA', 1),
        (N'CTP', N'COUNTER PAIN', 1),
        (N'CUB', N'CUBAN', 1),
        (N'CUK', N'CADBURY - UK', 1),
        (N'CUN', N'THE CHUAN', 1),
        (N'CUO', N'CULTI MILANO', 1),
        (N'CUT', N'CUTTY SARK', 1),
        (N'CVA', N'CALVALIER', 1),
        (N'DAI', N'DAIM', 1),
        (N'DAN', N'DANNEMANN', 1),
        (N'DAV', N'DAVIDOFF', 1),
        (N'DBH', N'DAVID BECKHAM', 1),
        (N'DBS', N'DR.BARBARA STURM', 1),
        (N'DCN', N'DEACON', 1),
        (N'DEC', N'COSME DECORTE', 1),
        (N'DEW', N'DEWAR''S', 1),
        (N'DGB', N'DOLCE & GABBANA', 1),
        (N'DHL', N'DUNHILL', 1),
        (N'DIE', N'DIESEL', 1),
        (N'DIH', N'CHRISTIAN DIOR HOMME', 1),
        (N'DIO', N'CHRISTIAN DIOR', 1),
        (N'DIP', N'DIPLOMATICO', 1),
        (N'DJI', N'DJI', 1),
        (N'DKF', N'Doi Kham Food', 1),
        (N'DLM', N'DALMORE', 1),
        (N'DMA', N'DEMAHEU', 1),
        (N'DNJ', N'DON JULIO', 1),
        (N'DOT', N'DOI TUNG', 1),
        (N'DPP', N'DON PAPA AGED RUM', 1),
        (N'DPW', N'DUTY PAID WINE', 1),
        (N'DRE', N'DRUNK ELEPHANT', 1),
        (N'DRM', N'DRUMS EXCELLENT', 1),
        (N'DRW', N'DREW ESTATE', 1),
        (N'DRX', N'DUREX', 1),
        (N'DSM', N'DIAGEO SPECIAL MALT', 1),
        (N'DTQ', N'DIPTYQUE', 1),
        (N'DTT', N'DETTOL', 1),
        (N'DVD', N'DAVIDOFF CIGARETTE', 1),
        (N'DVE', N'DOVE', 1),
        (N'DVM', N'DIVOOM', 1),
        (N'DWN', N'DALWHINNIE', 1),
        (N'DWT', N'DANIEL WELLINGTON', 1),
        (N'DZK', N'DANZKA', 1),
        (N'EAR', N'EMPORIO ARMANI', 1),
        (N'EDB', N'EVIDENS DE BEAUTE', 1),
        (N'EKA', N'EKAWAT  INDRACHAI', 1),
        (N'ELV', N'ELVAN', 1),
        (N'EPN', N'ESPOLON', 1),
        (N'ESS', N'ESSE', 1),
        (N'EST', N'ESTEE LAUDER', 1),
        (N'EVN', N'EVIAN', 1),
        (N'FAL', N'FALLING RAIN', 1),
        (N'FAN', N'FANTA', 1),
        (N'FEI', N'FEITAS', 1),
        (N'FEN', N'FENDI', 1),
        (N'FER', N'SALVATORE FERRAGAMO', 1),
        (N'FGR', N'FAMOUS GROUSE', 1),
        (N'FLK', N'FLIK FLAK', 1),
        (N'FMM', N'FLEMOMILE', 1),
        (N'FNE', N'FEARLESSNESS', 1),
        (N'FOP', N'FOUR PILLARS', 1),
        (N'FOS', N'FOSSIL', 1),
        (N'FRC', N'FERRERO ROCHER', 1),
        (N'FRH', N'FRESH', 1),
        (N'FRM', N'FRANCK MULLER', 1),
        (N'FRO', N'FOREO', 1),
        (N'FRW', N'FURONGWANG', 1),
        (N'FTW', N'FORTIFIED WINE', 1),
        (N'FUJ', N'FUJI', 1),
        (N'FUR', N'FURLA', 1),
        (N'GAE', N'GRANDE', 1),
        (N'GAR', N'GIORGIO ARMANI', 1),
        (N'GDV', N'GLEN DEVERON', 1),
        (N'GFD', N'GLENFIDDICH', 1),
        (N'GIV', N'GIVENCHY', 1),
        (N'GLD', N'GLENDRONACH', 1),
        (N'GLN', N'GUERLAIN', 1),
        (N'GLS', N'GAULOISES', 1),
        (N'GLT', N'GLEN GRANT', 1),
        (N'GLV', N'GLENLIVET', 1),
        (N'GMR', N'GLENMORANGIE', 1),
        (N'GNR', N'GIN MARE', 1),
        (N'GOC', N'GOLD CROSS', 1),
        (N'GOD', N'GODIVA', 1),
        (N'GON', N'GOLDEN VIRGINIA', 1),
        (N'GOR', N'GORDON''S', 1),
        (N'GOT', N'GO TRAVEL', 1),
        (N'GRA', N'GRANTS', 1),
        (N'GRG', N'GREY GOOSE', 1),
        (N'GRR', N'SEEBERGER', 1),
        (N'GRS', N'GRAND SEIKO', 1),
        (N'GRY', N'GLEN MORAY', 1),
        (N'GSK', N'GOLD SILK', 1),
        (N'GUC', N'GUCCI', 1),
        (N'GUE', N'GUESS', 1),
        (N'GUI', N'GUIYAN', 1),
        (N'GYL', N'GUYLIAN', 1),
        (N'HAB', N'HARIBO', 1),
        (N'HAM', N'HARMAN KARDON', 1),
        (N'HAW', N'HAWAIIAN HOST', 1),
        (N'HBS', N'HUGO BOSS', 1),
        (N'HDK', N'HENDRICKS', 1),
        (N'HDO', N'HIRUDOID', 1),
        (N'HDP', N'HANDPICKED', 1),
        (N'HEN', N'HENNESSY', 1),
        (N'HER', N'HERMES', 1),
        (N'HGR', N'HUNGARIAN WINE', 1),
        (N'HIG', N'HIGHLAND PARK', 1),
        (N'HMT', N'HAMILTON', 1),
        (N'HNG', N'Thai Herbal Hong Thai', 1),
        (N'HNT', N'HANUTA', 1),
        (N'HRB', N'HELENA RUBINSTEIN', 1),
        (N'HRG', N'HOURGLASS', 1),
        (N'HRI', N'HARISON', 1),
        (N'HSC', N'HIRUSCAR', 1),
        (N'HSS', N'HERSHEY''S', 1),
        (N'HTH', N'HONG THONG', 1),
        (N'HTK', N'HATAKABB', 1),
        (N'HUA', N'HUANTAI', 1),
        (N'HWI', N'HUAWEI', 1),
        (N'ILI', N'ILIADIN', 1),
        (N'IND', N'INDIGO HOME', 1),
        (N'INK', N'INNISKILLIN', 1),
        (N'IRO', N'IRON BALL', 1),
        (N'ISC', N'ISCORE', 1),
        (N'ITA', N'ITALASIA', 1),
        (N'ITL', N'ITALIAN WINE', 1),
        (N'IWC', N'IWC', 1),
        (N'IWS', N'INDEPENDENT WINE & SPIRIT', 1),
        (N'J&B', N'J & B', 1),
        (N'JAM', N'JAMESON', 1),
        (N'JBL', N'JBL', 1),
        (N'JBM', N'JIM BEAM', 1),
        (N'JDA', N'JEDA SAUSAGE', 1),
        (N'JDN', N'JACK DANIEL', 1),
        (N'JFI', N'J FRUIT', 1),
        (N'JGM', N'JAGER MEISTER', 1),
        (N'JLB', N'JELLY BEAN', 1),
        (N'JLC', N'JAEGER LE COULTRE', 1),
        (N'JMC', N'JIMMY CHOO', 1),
        (N'JML', N'JO MALONE', 1),
        (N'JPG', N'JEAN PAUL GAULTIER', 1),
        (N'JWK', N'JOHNNIE WALKER', 1),
        (N'KAG', N'KAGI', 1),
        (N'KAH', N'KAHLUA', 1),
        (N'KAV', N'KAVALAN', 1),
        (N'KEN', N'KENZO', 1),
        (N'KHL', N'KIEHL''S', 1),
        (N'KHW', N'KHWANTA', 1),
        (N'KIB', N'KI NO BI', 1),
        (N'KIN', N'KINDER', 1),
        (N'KIP', N'KIPLING', 1),
        (N'KIT', N'KIT KAT', 1),
        (N'KMA', N'KING POWER MAHANAKHONSKYWALK', 1),
        (N'KMH', N'MAHANAKHON', 1),
        (N'KMM', N'KRAAM MING MUK', 1),
        (N'KNP', N'KNOPPERS', 1),
        (N'KNT', N'KENT', 1),
        (N'KPR', N'KING POWER ROLL', 1),
        (N'KPS', N'KING POWER SELECTION', 1),
        (N'KRO', N'KRONGTHIP', 1),
        (N'KRS', N'KERASTASE', 1),
        (N'KSE', N'KOSE', 1),
        (N'KTL', N'KRISTALL', 1),
        (N'KYA', N'KAYA BATIK', 1),
        (N'KYE', N'KYLIE COSMETICS', 1),
        (N'L&M', N'L&M', 1),
        (N'LAB', N'LAB SERIES', 1),
        (N'LAG', N'LAGAVULIN', 1),
        (N'LAR', N'LARSEN', 1),
        (N'LB5', N'LABEL 5', 1),
        (N'LCA', N'LANCASTER', 1),
        (N'LCM', N'LANCOME', 1),
        (N'LCS', N'LACOSTE', 1),
        (N'LES', N'LE SPORTSAC', 1),
        (N'LGE', N'Longtime Cigar', 1),
        (N'LGM', N'LONGMORN', 1),
        (N'LGR', N'LA GALERA', 1),
        (N'LIN', N'LINDT', 1),
        (N'LJH', N'LIM JING HIENG', 1),
        (N'LLB', N'LE LABO', 1),
        (N'LLF', N'LEELAFAI', 1),
        (N'LMB', N'LAMBERT & BUTLER', 1),
        (N'LME', N'LA MER', 1),
        (N'LNE', N'LANEIGE', 1),
        (N'LNG', N'LONGINES', 1),
        (N'LNV', N'LANVIN', 1),
        (N'LOA', N'LOACKER', 1),
        (N'LOC', N'L''OCCITANE', 1),
        (N'LOE', N'LOEWE', 1),
        (N'LON', N'LONGCHAMP', 1),
        (N'LOR', N'L''OREAL', 1),
        (N'LPE', N'LA PRAIRIE', 1),
        (N'LPR', N'LAPHROAIG', 1),
        (N'LRS', N'LA ROCHE POSAY', 1),
        (N'LSK', N'LUCKY STRIKE', 1),
        (N'LTC', N'LEICESTER CITY', 1),
        (N'LUP', N'LU Petit Ecolier', 1),
        (N'M&B', N'MIND & BODY', 1),
        (N'M&C', N'MOET & CHANDON', 1),
        (N'M&M', N'M & M', 1),
        (N'MAH', N'MEKHONG', 1),
        (N'MAL', N'MALIBU', 1),
        (N'MAR', N'MARTELL', 1),
        (N'MAT', N'MASITA', 1),
        (N'MAV', N'MARVIS', 1),
        (N'MBA', N'MAMBA', 1),
        (N'MBR', N'MARLBORO', 1),
        (N'MCC', N'MAC', 1),
        (N'MCJ', N'MARC JACOBS', 1),
        (N'MCK', N'MICHAEL KORS', 1),
        (N'MCL', N'THE MACALLAN', 1),
        (N'MCM', N'MCM', 1),
        (N'MCR', N'MANN CRAFT', 1),
        (N'MCT', N'MANCHESTER', 1),
        (N'MEN', N'MENTOS', 1),
        (N'MER', N'MERCI', 1),
        (N'MFK', N'MAISON FRANCIS KURKDJIAN', 1),
        (N'MFY', N'MALFY', 1),
        (N'MGL', N'MAISON MARGIELA', 1),
        (N'MID', N'MIDO', 1),
        (N'MIJ', N'MAUI JIM', 1),
        (N'MIU', N'MIU MIU', 1),
        (N'MJD', N'MAAJAIDUM', 1),
        (N'MKA', N'MILKA', 1),
        (N'MKF', N'MONKEY 47', 1),
        (N'MKW', N'MILKY WAY', 1),
        (N'MKY', N'MONKEY SHOULDER', 1),
        (N'ML7', N'MEVIUS', 1),
        (N'MLA', N'MALAI', 1),
        (N'MMK', N'MAKER''S MARK', 1),
        (N'MMY', N'MOO TUB MUAD YOO', 1),
        (N'MNL', N'MONCLER', 1),
        (N'MON', N'MONTBLANC', 1),
        (N'MOT', N'MOUTAI', 1),
        (N'MRD', N'MERIDIAN', 1),
        (N'MRS', N'MARS', 1),
        (N'MRW', N'MINERAL WATER', 1),
        (N'MSH', N'MARSHALL', 1),
        (N'MTN', N'MARTINI', 1),
        (N'MTS', N'MALTESERS', 1),
        (N'MUF', N'MAKE UP FOR EVER', 1),
        (N'MUN', N'MUNZ', 1),
        (N'MYK', N'ISSEY MIYAKE', 1),
        (N'NAE', N'NATEAR', 1),
        (N'NAR', N'NARS', 1),
        (N'NCD', N'NINECHAIDEE', 1),
        (N'NCS', N'NARCISO RODRIGUEZ', 1),
        (N'NDG', N'NODOGLE', 1),
        (N'NEB', N'NEOBUN', 1),
        (N'NES', N'NESTLE', 1),
        (N'NEU', N'NEUHAUS', 1),
        (N'NII', N'NIMM', 1),
        (N'NIT', N'NINTENDO', 1),
        (N'NLH', N'NATURELIFEHERB', 1),
        (N'NMM', N'NAMMAN MUAY', 1),
        (N'NMO', N'NATAMON', 1),
        (N'NMT', N'NAMTHIP', 1),
        (N'NOV', N'MOUTAI BULAO', 1),
        (N'NRB', N'NEUROBION', 1),
        (N'NTE', N'NITREE', 1),
        (N'NTM', N'NUTRIMATE', 1),
        (N'NTR', N'NINE TAMARIND', 1),
        (N'NUT', N'NUTELLA', 1),
        (N'OAK', N'OAKLEY', 1),
        (N'OBN', N'OBAN', 1),
        (N'OFC', N'Other French Champagne', 1),
        (N'OIA', N'OLIVA', 1),
        (N'OLE', N'OLAPLEX', 1),
        (N'OMC', N'OLMECA', 1),
        (N'OME', N'OMEGA', 1),
        (N'ONN', N'ON', 1),
        (N'OPA', N'OLD PARR', 1),
        (N'OPT', N'OLD PULTENEY', 1),
        (N'ORE', N'OREO', 1),
        (N'ORN', N'ORIGINS', 1),
        (N'OSS', N'SOS PLUS', 1),
        (N'OSW', N'OVER SIZE WINES', 1),
        (N'OTF', N'OTHER FRENCH WINE', 1),
        (N'OTP', N'OTOP SELECTION', 1),
        (N'OVO', N'OVOMALTINE', 1),
        (N'PAM', N'PANERAI', 1),
        (N'PAW', N'PAWINEE', 1),
        (N'PCH', N'PATCHI', 1),
        (N'PCO', N'PACO RABANNE', 1),
        (N'PDP', N'PHAYDOKPLUI', 1),
        (N'PEA', N'PLEONTA', 1),
        (N'PEC', N'PENCE', 1),
        (N'PEP', N'PEPE LOPES', 1),
        (N'PHG', N'PENHALIGON', 1),
        (N'PHI', N'PHILIPS', 1),
        (N'PHK', N'PHU KLON', 1),
        (N'PHY', N'PHRAYA', 1),
        (N'PJN', N'PAUL JOHN', 1),
        (N'PKI', N'PRAKAI THAI SILK', 1),
        (N'PL8', N'Pastel Life Club', 1),
        (N'PLC', N'POLA', 1),
        (N'PLE', N'PLERN', 1),
        (N'PLR', N'POLAROID', 1),
        (N'PNF', N'PENFOLDS', 1),
        (N'POI', N'POLICE', 1),
        (N'POL', N'POLO RALPH LAUREN', 1),
        (N'POW', N'PRONPUN  WIWITTHAKHUN', 1),
        (N'PPS', N'POP THEPHASIT', 1),
        (N'PRA', N'PRADA', 1),
        (N'PRG', N'PRINGLES', 1),
        (N'PRS', N'PRADA SPORT', 1),
        (N'PRU', N'PEERASUK HNOOPHET', 1),
        (N'PSO', N'PRASONG', 1),
        (N'PTR', N'PATRON', 1),
        (N'PUE', N'PUEBLO', 1),
        (N'PW8', N'PASTEL CREATE WEAR', 1),
        (N'PWK', N'PHRAE WA KALASIN', 1),
        (N'PX8', N'PASTELCREATIVE', 1),
        (N'QLY', N'QUALITY STREET', 1),
        (N'RAD', N'RADO WATCH', 1),
        (N'RAY', N'RAYBAN', 1),
        (N'RBS', N'REDBREAST', 1),
        (N'RCD', N'ROYAL CHITRALADAPROJECT', 1),
        (N'REC', N'REGENCY', 1),
        (N'REM', N'REMY MARTIN', 1),
        (N'RES', N'REESE''S', 1),
        (N'RIC', N'RICARD', 1),
        (N'RIF', N'RIFAI', 1),
        (N'RII', N'RII', 1),
        (N'RIL', N'RIZLA', 1),
        (N'RIS', N'RIESEN', 1),
        (N'RIV', N'RIVER', 1),
        (N'RKP', N'ROCKY PATEL', 1),
        (N'RKS', N'RUANG KHAO', 1),
        (N'RLN', N'RALPH LAUREN', 1),
        (N'ROE', N'PEPERO', 1),
        (N'ROL', N'ROLEX', 1),
        (N'RPD', N'DOI KHAM', 1),
        (N'RPF', N'ROYAL PROJECT', 1),
        (N'RPK', N'PRAKAAN', 1),
        (N'RSL', N'ROYAL SALUTE', 1),
        (N'RTL', N'RITUALS', 1),
        (N'RTS', N'RITTER SPORT', 1),
        (N'RUK', N'RUKBAIK', 1),
        (N'S0T', N'SOTHING', 1),
        (N'SAM', N'SAMSONITE', 1),
        (N'SAS', N'SAMSUNG', 1),
        (N'SBC', N'SRIBUNGLERD COTTON', 1),
        (N'SBU', N'SAMBUCOL', 1),
        (N'SCG', N'SCANDINAVIAN TOBACCO GROUP', 1),
        (N'SCW', N'SCHWEPPES', 1),
        (N'SDK', N'SANDISK', 1),
        (N'SEI', N'SEIKO', 1),
        (N'SER', N'SAMER', 1),
        (N'SEW', N'SIR EDWARD''S', 1),
        (N'SFE', N'SOFFELL', 1),
        (N'SG1', N'SATOGESIC', 1),
        (N'SGK', N'SURANAREE GOLD SILK', 1),
        (N'SHH', N'SHEDE', 1),
        (N'SHI', N'SHISEIDO', 1),
        (N'SHJ', N'SHUI JING FANG', 1),
        (N'SHS', N'SENNHEISER', 1),
        (N'SHU', N'SHU UEMURA', 1),
        (N'SHZ', N'SHOKZ', 1),
        (N'SIS', N'SISLEY', 1),
        (N'SIW', N'STONE ISLAND', 1),
        (N'SJT', N'SAI JAI THAI', 1),
        (N'SK2', N'SKII', 1),
        (N'SKT', N'SKITTLES', 1),
        (N'SLP', N'SALONPAS', 1),
        (N'SLT', N'SINGLETON', 1),
        (N'SMA', N'SMARTIES', 1),
        (N'SMI', N'SMIRNOFF', 1),
        (N'SNB', N'SNAKE BRAND', 1),
        (N'SNK', N'SNICKER', 1),
        (N'SNW', N'SPANISH WINE', 1),
        (N'SOA', N'SOPHASOAP', 1),
        (N'SON', N'SONY', 1),
        (N'SOS', N'SANG SOM', 1),
        (N'SRA', N'SOMPRASONG', 1),
        (N'SRM', N'ST REMY', 1),
        (N'SRR', N'SIRIWAN REANTHONGCHAI', 1),
        (N'SRT', N'SURAT', 1),
        (N'SRZ', N'SPRITE', 1),
        (N'SSL', N'SENSAILAITIAN', 1),
        (N'SSS', N'SRIPA', 1),
        (N'STA', N'SEVEN STARS', 1),
        (N'STE', N'STERLING', 1),
        (N'SUH', N'SUPHIN', 1),
        (N'SUI', N'Sunsilk', 1),
        (N'SUN', N'SUNTORY', 1),
        (N'SUT', N'SUNTREE', 1),
        (N'SVC', N'SUVARNACHAD', 1),
        (N'SVS', N'SEVEN SEALS', 1),
        (N'SWA', N'SWAROVSKI', 1),
        (N'SWS', N'SULWHASOO', 1),
        (N'SWT', N'SWATCH', 1),
        (N'TAG', N'TAG HEUER', 1),
        (N'TAN', N'TANQUERAY', 1),
        (N'TAR', N'THAIAREE', 1),
        (N'TAY', N'TAYWA', 1),
        (N'TBL', N'TOBLERONE', 1),
        (N'TBV', N'THAI BEVERAGE', 1),
        (N'TCA', N'TOSCANO', 1),
        (N'TCO', N'TIFFANY', 1),
        (N'TEA', N'TEACHER''S', 1),
        (N'TEW', N'TEELING', 1),
        (N'TFD', N'TOM FORD', 1),
        (N'TGB', N'TIGER BALM', 1),
        (N'TIB', N'THONGSIRI INDIGO BLUE', 1),
        (N'TIC', N'TIC TAC', 1),
        (N'TIS', N'TISSOT', 1),
        (N'TLK', N'TALISKER', 1),
        (N'TMA', N'TOMATIN', 1),
        (N'TMY', N'TOMMY HILFIGER', 1),
        (N'TNL', N'TRINOLONE', 1),
        (N'TOF', N'TOFFIFEE', 1),
        (N'TPC', N'TROPICANA', 1),
        (N'TRB', N'TRAVEL BLUE', 1),
        (N'TRO', N'TROLLI', 1),
        (N'TRZ', N'TERRAZAS', 1),
        (N'TTN', N'TAI TAM NAK', 1),
        (N'TTO', N'TITO', 1),
        (N'TTR', N'SANTA TERESA', 1),
        (N'TTZ', N'TANGLE TEEZER', 1),
        (N'TUD', N'TUDOR', 1),
        (N'TUM', N'TUMI', 1),
        (N'TVB', N'TRAVELBLUE', 1),
        (N'TWP', N'THAWEEPHAN PRODUCT', 1),
        (N'TWX', N'TWIX', 1),
        (N'TXC', N'TEXICA', 1),
        (N'TYB', N'TORY BURCH', 1),
        (N'TYN', N'TYLENOL', 1),
        (N'TYS', N'TONY’S', 1),
        (N'UBB', N'UBBS', 1),
        (N'UDB', N'UNDERBERG', 1),
        (N'UDC', N'URBAN DECAY', 1),
        (N'VAL', N'VALENTINO', 1),
        (N'VAR', N'VARINTHIP', 1),
        (N'VCA', N'VAN CLEEF & ARPELS', 1),
        (N'VCP', N'VEUVE CLICQUOT PONS.', 1),
        (N'VED', N'VEDI VERO', 1),
        (N'VEN', N'VENCHI', 1),
        (N'VER', N'VERSACE', 1),
        (N'VIK', N'VICK''S', 1),
        (N'VIL', N'VILLIGER', 1),
        (N'VLO', N'VELO', 1),
        (N'VOG', N'VOGUE', 1),
        (N'VOL', N'VOLVIC', 1),
        (N'VSL', N'Vaseline', 1),
        (N'VTP', N'VITO', 1),
        (N'WAG', N'WANG PROM', 1),
        (N'WAP', N'WANPEN THAISILK', 1),
        (N'WDM', N'WONGDUENMATYOM', 1),
        (N'WER', N'WERTHERS', 1),
        (N'WFR', N'WOODFORD RESERVE', 1),
        (N'WGG', N'WINGGLEN', 1),
        (N'WGR', N'WINE GALLERY', 1),
        (N'WIN', N'WINSTON', 1),
        (N'WLM', N'WILDMOOR', 1),
        (N'WND', N'WONDER RED', 1),
        (N'WRI', N'WRIGLEY', 1),
        (N'WTK', N'WILD TURKEY', 1),
        (N'XQS', N'XQS', 1),
        (N'XUX', N'XUXU', 1),
        (N'XXX', N'TRIPLE X', 1),
        (N'YIN', N'YIN DEE', 1),
        (N'YOK', N'YOKI', 1),
        (N'YSL', N'YSL', 1),
        (N'YXI', N'YU XI', 1),
        (N'ZAM', N'ZAM-BUK', 1),
        (N'ZAR', N'SARA', 1),
        (N'ZCP', N'ZACAPA', 1),
        (N'ZEG', N'ZEGNA', 1),
        (N'ZIP', N'ZIPPO', 1),
        (N'ZRO', N'ZERO', 1),
        (N'999', N'DUMMY', 1)
) AS S ([Brand Code], [Brand Name], isActive)
ON T.[Brand Code] = S.[Brand Code]
WHEN MATCHED THEN
    UPDATE SET
        T.[Brand Name] = S.[Brand Name], T.isActive = S.isActive
WHEN NOT MATCHED BY TARGET THEN
    INSERT ([Brand Code], [Brand Name], isActive)
    VALUES (S.[Brand Code], S.[Brand Name], S.isActive);
GO

MERGE dbo.MS_Version AS T
USING
(
    VALUES
        (N'A1', N'Original', 1, 1),
        (N'R1', N'Revise', 1, 1),
        (N'R2', N'Revise', 2, 1),
        (N'R3', N'Revise', 3, 1)
) AS S (VersionCode, OTBTypeCode, Seq, isActive)
ON T.VersionCode = S.VersionCode AND T.OTBTypeCode = S.OTBTypeCode
WHEN MATCHED THEN
    UPDATE SET
        T.Seq = S.Seq, T.isActive = S.isActive
WHEN NOT MATCHED BY TARGET THEN
    INSERT (VersionCode, OTBTypeCode, Seq, isActive)
    VALUES (S.VersionCode, S.OTBTypeCode, S.Seq, S.isActive);
GO

MERGE dbo.MS_Vendor AS T
USING
(
    VALUES
        (N'1011398', N'GUCCI SERVICES (THAILAND) LTD.', N'THB', N'D30E', N'PAYLOCAL 30 DAYS FROM DELIVERY DATE', N'201', N'T/T Normal Pay local', N'CIF', 1),
        (N'1011275', N'Richemont Luxury (Thailand) Limited', N'THB', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'DAP', 1),
        (N'1011436', N'CELINE', N'EUR', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1010541', N'LUXOTTICA ITALIA SRL', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1011259', N'KERING EYEWEAR APAC LIMITED', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011359', N'THELIOS ASIA PACIFIC LIMITED', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1010060', N'SAFILO FAR EAST LTD.', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1010737', N'MARCOLIN SPA', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1010814', N'MARCHON EYEWEAR (HONG KONG) LTD.', N'HKD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010644', N'DE RIGO HONGKONG LIMITED', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011243', N'ARTGRI GROUP INTERNATIONAL PTE.LTD.', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011295', N'Whales and Co., LTD.', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1021205', N'SWAROVSKI (THAILAND) LIMITED', N'THB', N'D60I', N'PAYLOCAL 60 DAYS FROM INVOICE DATE', N'201', N'T/T Normal Pay local', N'CIP', 1),
        (N'1011281', N'YVES SAINT LAURENT LOGISTIC', N'USD', N'LCSG', N'L/C AT SIGHT', N'100', N'L/C Normal', N'EXW', 1),
        (N'1010220', N'FERRAGAMO HONG KONG LTD', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011329', N'Autumnpaper Ltd', N'USD', N'LCSG', N'L/C AT SIGHT', N'100', N'L/C Normal', N'EXW', 1),
        (N'1011422', N'Gianni Versace Srl', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011207', N'TORY BURCH FAR EAST LIMITED', N'USD', N'L30G', N'L/C 30 DAYS AFTER SIGHT', N'100', N'L/C Normal', N'EXW', 1),
        (N'1011339', N'INDUSTRIES SPA', N'USD', N'L30G', N'L/C 30 DAYS AFTER SIGHT', N'100', N'L/C Normal', N'FCA', 1),
        (N'1020181', N'THE SWATCH GROUP TRADING(THAILAND)', N'THB', N'D30D', N'PAYLOCAL 30 DAYS FROM BILLING DATE', N'201', N'T/T Normal Pay local', N'CIP', 1),
        (N'1011010', N'ROLEX SINGAPORE PRIVATE LIMITED', N'SGD', N'ADPV', N'ADVANCED PAYMENT', N'230', N'T/T Advance Payment', N'FOB', 1),
        (N'1011032', N'CHOPARD (ASIA) PTE LTD.', N'SGD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011275', N'Richemont Luxury (Thailand) Limited', N'THB', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'DAP', 1),
        (N'1010588', N'BVLGARI SOUTH ASIAN OPERATIONS', N'SGD', N'C30N', N'CREDIT 30 DAYS END OF MONTH OF INVOICE DATE', N'200', N'T/T Normal', N'DAP', 1),
        (N'1010130', N'FOSSIL ASIA PACIFIC LIMITED', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011452', N'Breitling South East Asia Pte Ltd', N'SGD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010453', N'CASIO COMPUTER CO.,LTD', N'USD', N'D60E', N'PAYLOCAL 60 DAYS FROM DELIVERY DATE', N'201', N'T/T Normal Pay local', N'FOB', 1),
        (N'1011568', N'LVMH Watch & Jewellery (Thailand) L', N'THB', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'DAP', 1),
        (N'1010466', N'HERMES ASIA PACIFIC LIMITED', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010140', N'LUXURY TIMEPIECES (HK) LIMITED.', N'HKD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011305', N'DANIEL WELLINGTON AB', N'USD', N'C45B', N'CREDIT 45 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010626', N'FREDERIQUE CONSTANT SA', N'EUR', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011303', N'FIYTA (HONG KONG) LIMITED', N'USD', N'C45B', N'CREDIT 45 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011205', N'SHENZHEN FIYTA PRECISION SCIENCE', N'USD', N'C45B', N'CREDIT 45 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010617', N'SWISSAM PRODUCTS LIMITED (SPL)', N'EUR', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011217', N'WAH MING HONG LIMITED', N'HKD', N'C30B', N'CREDIT 30 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011002', N'FOLLI FOLLIE ASIA LIMITED', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1010995', N'FRANCK MULLER PTE LTD', N'SGD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011560', N'Bell & Ross Singapore Pte.Ltd.', N'SGD', N'C60A', N'CREDIT 60 DAYS FROM ARRIVAL DATE', N'200', N'T/T Normal', N'DDU', 1),
        (N'1011126', N'TIME PRODUCTS UK LIMITED', N'USD', N'C75I', N'CREDIT 75 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011288', N'PANAMERA FASHION CO.,LTD', N'THB', N'D60D', N'PAYLOCAL 60 DAYS FROM BILLING DATE', N'201', N'T/T Normal Pay local', N'CIP', 1),
        (N'1011273', N'WMA (WISE MEN ALLIANCE) PTE LTD.', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1020032', N'SEIKO (THAILAND ) CO.,LTD.', N'THB', N'C90D', N'CREDIT 90 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1022168', N'LDI Enterprise (Thailand) Limited', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1020784', N'Chanel (Thailand) Limited', N'THB', N'D30I', N'PAYLOCAL 30 DAYS FROM INVOICE DATE', N'201', N'T/T Normal Pay local', N'CIP', 1),
        (N'1011414', N'APM MONACO SAM', N'THB', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010193', N'FENDI S.R.L.', N'EUR', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1011425', N'Loewe SA', N'EUR', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011274', N'BOTTEGA VENETA S.R.L.', N'EUR', N'LCSG', N'L/C AT SIGHT', N'100', N'L/C Normal', N'EXW', 1),
        (N'1010078', N'RICHEMONT ASIA PACIFIC LTD', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010977', N'GIORGIO ARMANI S.P.A', N'EUR', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011266', N'COACH OPERATIONS SINGAPORE PTE LTD.', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011412', N'Marc Jacobs International LLC', N'USD', N'L45I', N'L/C 45 DAYS FROM INVOICE DATE', N'100', N'L/C Normal', N'EXW', 1),
        (N'1011420', N'PANDORA JEWELRY PTY LIMITED', N'AUD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'DAP', 1),
        (N'1010935', N'THOMAS SABO GMBH & CO.KG', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1022077', N'THE SWATCH GROUP TRADING', N'THB', N'D30D', N'PAYLOCAL 30 DAYS FROM BILLING DATE', N'201', N'T/T Normal Pay local', N'CIP', 1),
        (N'1011390', N'Gucci Swiss Timepieces SA,', N'HKD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'DDP', 1),
        (N'1011557', N'GROUPE 1602 BV', N'USD', N'ADDP', N'DUTY PAID ADVANCED PAYMENT', N'232', N'T/T Duty Paid Advance', N'FCA', 1),
        (N'1011554', N'CULTI MILANO S.P.A', N'EUR', N'ADDP', N'DUTY PAID ADVANCED PAYMENT', N'232', N'T/T Duty Paid Advance', N'EXW', 1),
        (N'1020821', N'LUXASIA (SIAM) CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1022354', N'COTY OPERATIONS (THAILAND) CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1022355', N'SHISEIDO (THAILAND) COMPANY LIMITED', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1022377', N'OC TRADING (THAILAND) CO., LTD.', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021457', N'ZUELLIG PHARMA CO.,LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1022364', N'SIRENNA GROUP CO., LTD.', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1022385', N'G3 (TH) CO.,LTD.', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021594', N'FUJIFILM (THAILAND) LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021739', N'ASH ASIA INTERNATIONAL LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021135', N'KOAN CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020622', N'SONY THAI CO.,LTD.', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1020789', N'MAHAJAK DEVELOPMENT CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1022360', N'PERM POON PATANA INDUSTRY CO., LTD', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1022359', N'PRESTIGE SELECTION CO.,LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1011405', N'Balenciaga S.A.S.', N'EUR', N'LCSG', N'L/C AT SIGHT', N'100', N'L/C Normal', N'EXW', 1),
        (N'1010636', N'BURBERRY(SINGAPORE)DISTRIBUTION', N'SGD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1010094', N'BVLGARI IRELAND LTD', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011254', N'PVH ASIA LTD.', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1010631', N'COACH OPERATIONS SINGAPORE PTE LTD', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1010610', N'FURLA (HK) LIMITED', N'EUR', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010900', N'HUGO BOSS SOUTH EAST ASIA PTE.LTD', N'EUR', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1011154', N'MONTAIGNE HONG KONG LIMITED', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010049', N'S.A.S LONGCHAMP', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011206', N'MICHAEL KORS LIMITED HONG KONG', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011009', N'MCM FASHION GROUP LIMITED', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011354', N'Ralph Lauren Asia Pacific Ltd', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011549', N'SPORTSWEAR COMPANY SPA', N'EUR', N'L30I', N'L/C 30 DAYS FROM INVOICE DATE', N'100', N'L/C Normal', N'FCA', 1),
        (N'1010578', N'TUMI ASIA LTD.', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011548', N'CONSITEX SA', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1010044', N'VF Singapore Overseas Services Pte.', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011436', N'CELINE', N'EUR', N'LCSG', N'L/C AT SIGHT', N'100', N'L/C Normal', N'EXW', 1),
        (N'1011567', N'CANADA GOOSE ASIA HOLDINGS LIMITED', N'CAD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011292', N'DESIGN GO (ASIA) LIMITED', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011425', N'Loewe SA', N'EUR', N'C15I', N'CREDIT 15 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1010531', N'SAMSONITE SINGAPORE PTE LTD', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011072', N'TRAVEL BLUE LTD', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1020161', N'AMBROSE WINE LIMITED', N'THB', N'D60D', N'PAYLOCAL 60 DAYS FROM BILLING DATE', N'201', N'T/T Normal Pay local', N'LOD', 1),
        (N'1010487', N'BEAM SUNTORY ASIA PTE LTD', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010319', N'BOTTEGA SPA', N'EUR', N'C90I', N'CREDIT 90 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010300', N'BROWN-FORMAN BEVERAGES WORLDWIDE', N'USD', N'C90I', N'CREDIT 90 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011385', N'CAMPARI SINGAPORE PTE. LTD.', N'USD', N'C90I', N'CREDIT 90 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010417', N'CAMUS WINES & SPIRITS', N'EUR', N'C90I', N'CREDIT 90 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011388', N'CASK AWAY PTE LTD.', N'USD', N'C60C', N'CREDIT 60 DAYS FROM B/L DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011362', N'CHAT NOIR CO. INC.', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010771', N'CHOYA UMESHU SOUTH EAST ASIA', N'JPY', N'C60C', N'CREDIT 60 DAYS FROM B/L DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010261', N'DIAGEO SCOTLAND LIMITED', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011214', N'EDRINGTON SINGAPORE PTE LTD', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011434', N'FORTIER WINES & SPIRITS', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011439', N'GLOBAL DRINKS LIMITED', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011380', N'HEALESVILLE DISTILLING PTY LTD', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1020958', N'INDEPENDENT WINE & SPIRIT', N'THB', N'D30E', N'PAYLOCAL 30 DAYS FROM DELIVERY DATE', N'201', N'T/T Normal Pay local', N'CFR', 1),
        (N'1011098', N'INTERBEV (SINGAPORE) LIMITED', N'GBP', N'C12I', N'CREDIT 120 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010988', N'Moet Hennessy Asia Pacific Pte Ltd.', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011462', N'NOVACORP PTE. LTD.', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010234', N'PERNOD RICARD HONG KONG LIMITED', N'USD', N'C75C', N'CREDIT 75 DAYS FROM B/L DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011453', N'RED BULL DISTILLERY (1988) CO.,LTD.', N'THB', N'D45D', N'PAYLOCAL 45 DAYS FROM BILLING DATE', N'201', N'T/T Normal Pay local', N'DAP', 1),
        (N'1010302', N'REMY COINTREAU INTERNATIONAL PTE', N'USD', N'C60C', N'CREDIT 60 DAYS FROM B/L DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010831', N'SEMPER IDEM UNDERBERG AG', N'EUR', N'C60C', N'CREDIT 60 DAYS FROM B/L DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1020889', N'SIAM DRAGON (ASIA-PACIFIC) CO.,', N'THB', N'D30D', N'PAYLOCAL 30 DAYS FROM BILLING DATE', N'201', N'T/T Normal Pay local', N'LOD', 1),
        (N'1011456', N'FAMOBRA PTE LTD', N'USD', N'C45E', N'CREDIT 45 DAYS FROM DELIVERY DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010457', N'MARKET FORCE (ASIA) LTD', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011542', N'PINK AND TAN CO., LTD.', N'THB', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'LOD', 1),
        (N'1011440', N'ALCHEMY WINES AND SPIRITS', N'THB', N'C60E', N'CREDIT 60 DAYS FROM DELIVERY DATE', N'200', N'T/T Normal', N'LOD', 1),
        (N'1010304', N'TRADALL S.A', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011202', N'WALDEMAR BEHN', N'EUR', N'C90I', N'CREDIT 90 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011192', N'WHYTE AND MACKAY LIMITED', N'USD', N'C90I', N'CREDIT 90 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010271', N'WILLIAM GRANT & SONS BRANDS LTD.', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011459', N'WINGGLEN PTE LTD', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011372', N'BAR SAR CIGARETTE INTERNATIONAL', N'THB', N'D30E', N'PAYLOCAL 30 DAYS FROM DELIVERY DATE', N'201', N'T/T Normal Pay local', N'CIF', 1),
        (N'1011083', N'BAT GLOBAL TRAVEL RETAIL LIMITED', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010461', N'CHINA TOBACCO INTERNATIONAL (HK)', N'USD', N'LCSG', N'L/C AT SIGHT', N'100', N'L/C Normal', N'CFR', 1),
        (N'1011338', N'CIGRAAL LIMITED', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010298', N'DAVIDOFF OF GENEVA HONG KONG', N'HKD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1011197', N'Yechco Sdn Bhd', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1020657', N'HONGTHAI INTERNATIONAL TRADING', N'USD', N'D60I', N'PAYLOCAL 60 DAYS FROM INVOICE DATE', N'201', N'T/T Normal Pay local', N'CIF', 1),
        (N'1011407', N'IMPERIAL TOBACCO INTERNATIONAL GMBH', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011264', N'JT INTERNATIONAL SINGAPORE PTE.LTD.', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011366', N'LONGTIME COMPANY LIMITED', N'HKD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011108', N'LUBRITRADE TRADING PTE LTD', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011437', N'NEW PORT DUTY FREE PTE LTD', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010979', N'PEJADY CORPORATION PTE LTD.', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010251', N'THE PACIFIC CIGAR COMPANY (MACAU) L', N'HKD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010255', N'TOBACCO TRADERS INTERNATIONAL LTD.', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011570', N'ACEWIDE ASIA PTE LTD', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010099', N'GODIVA TRA LIMITED', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011282', N'PREMIUM CHOCOLATES AND', N'USD', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010879', N'NEUHAUS NV', N'EUR', N'C30I', N'CREDIT 30 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011460', N'LOTTE WELLFOOD CO., LTD.', N'USD', N'C45C', N'CREDIT 45 DAYS FROM B/L DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010147', N'HAWAIIAN HOST HONOLULU INC.', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CFR', 1),
        (N'1010128', N'FOCUS NETWORK AGENCIES (S) PTE LTD.', N'SGD', N'C60C', N'CREDIT 60 DAYS FROM B/L DATE', N'200', N'T/T Normal', N'CFR', 1),
        (N'1011544', N'Maestrani Schweizer Schokoladen AG', N'CHF', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011151', N'HIMAN TRADING COMPANY LIMITED', N'USD', N'C60C', N'CREDIT 60 DAYS FROM B/L DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1010170', N'MONDELEZ WORLD TRAVEL RETAIL LLC', N'CHF', N'C90I', N'CREDIT 90 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1010200', N'NESTLE ENTERPRISES S.A.', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1010845', N'Perfetti Van Melle Nederland B.V.', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010178', N'LINDT & SPRUNGLI (SCHWEIZ) AG', N'CHF', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1010436', N'CHOCOLATES GUYLIAN N.V.', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011384', N'SWEET GARDEN FZCO', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011365', N'A. LOACKER SPA/AG', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011457', N'VENCHI HK LIMITED', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010190', N'MARS INTERNATIONAL TRAVEL', N'EUR', N'C75I', N'CREDIT 75 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011159', N'BUTLERS CHOCOLATES CO., LTD.', N'EUR', N'C90C', N'CREDIT 90 DAYS FROM B/L DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011234', N'ALFRED RITTER GMBH & CO.KG', N'EUR', N'C90I', N'CREDIT 90 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011564', N'SEEBERGER GMBH', N'EUR', N'C75I', N'CREDIT 75 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010908', N'LOUIS VIALARD S.A.S.', N'EUR', N'ADPV', N'ADVANCED PAYMENT', N'230', N'T/T Advance Payment', N'EXW', 1),
        (N'1011102', N'JOANNE', N'EUR', N'ADPV', N'ADVANCED PAYMENT', N'230', N'T/T Advance Payment', N'EXW', 1),
        (N'1011239', N'BARTON & GUESTIER', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011248', N'FARR VINTNERS LTD', N'GBP', N'ADPV', N'ADVANCED PAYMENT', N'230', N'T/T Advance Payment', N'EXW', 1),
        (N'1011256', N'C.V.B.G.', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'EXW', 1),
        (N'1011238', N'PENFOLDS WINES INTERNATIONAL', N'AUD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1011458', N'ARTERRA WINES CANADA INC.', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010787', N'ITALASIA TRADING(THAILAND) CO.,LTD.', N'THB', N'D45D', N'PAYLOCAL 45 DAYS FROM BILLING DATE', N'201', N'T/T Normal Pay local', N'LOD', 1),
        (N'1020749', N'BANGKOK BEER AND BEVERAGES CO.,LTD.', N'THB', N'D60D', N'PAYLOCAL 60 DAYS FROM BILLING DATE', N'201', N'T/T Normal Pay local', N'LOD', 1),
        (N'1022146', N'15 DEGREE CO.,LTD.', N'THB', N'ADLP', N'LOCAL ADVANCED PAYMENT', N'310', N'Advance Local', NULL, 1),
        (N'1021414', N'ABERDEEN LE HAVRE CO., LTD.', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1022034', N'ALCHEMY WINES & SPIRITS', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1022001', N'EAST BATAVIA CO., LTD.', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1021684', N'H.P. SUPPLY MARKETING CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1021568', N'LAMAI DISTILLERIES COMPANY LIMITED', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1021454', N'MAAJAIDUM CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1020580', N'NUM YUK CO.,LTD.', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1021410', N'PERNOD RICARD (THAILAND) LIMITED', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1021520', N'PREMIUM THAI BRANDS CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1021994', N'SANGSOM CO., LTD.', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1020279', N'ST.SUPPORT LIQUER LTD.,PART', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1022210', N'SUNTORN TRADING CO., LTD.', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1021858', N'SURA BANGYIKHAN CO., LTD.', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1021652', N'TEXICA CO., LTD.', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1021937', N'WINE GALLERY CO., LTD.', N'THB', N'ADLP', N'LOCAL ADVANCED PAYMENT', N'310', N'Advance Local', NULL, 1),
        (N'1020428', N'TOBACCO AUTHORITY OF THAILAND', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', N'LOD', 1),
        (N'1022220', N'UNITED WINERY AND DISTILLERY', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1010866', N'SHISEIDO TRAVEL RETAIL ASIA', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011423', N'ASC Regenity Limited', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010123', N'ESTEE LAUDER A.G. LACHEN', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011319', N'L BEAUTY PTE, LTD.', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011565', N'Charlottet Tilbury Beauty Hong Kong', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1010233', N'L''Oreal Travel Retail Asia Pacific,', N'THB', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011301', N'Coty Operations Asia Pacific Pte', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1010208', N'LVMH Fragrances and Cosmetics Singa', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1010331', N'CLARINS PTE.,LTD', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011343', N'KOSE CORPORATION', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011545', N'DOLCE & GABBANA BEAUTY S.r.l.', N'EUR', N'C75I', N'CREDIT 75 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010120', N'ELIZABETH ARDEN INTERNATIONAL,', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011393', N'LVMH Fragrances and Cosmetics', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'DAP', 1),
        (N'1010207', N'LVMH Fragrances and Cosmetics', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1010142', N'LVMH FRAGRANCES & COSMETICS-', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1010442', N'HERMES PARFUMS', N'EUR', N'C30N', N'CREDIT 30 DAYS END OF MONTH OF INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011404', N'UPD (Thailand) Co.,Ltd', N'THB', N'D60I', N'PAYLOCAL 60 DAYS FROM INVOICE DATE', N'201', N'T/T Normal Pay local', N'DDP', 1),
        (N'1011344', N'KOSE (THAILAND) CO.,LTD.', N'THB', N'D60I', N'PAYLOCAL 60 DAYS FROM INVOICE DATE', N'201', N'T/T Normal Pay local', N'DAP', 1),
        (N'1011123', N'AMOREPACIFIC CORPORATION', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010580', N'LA PRAIRIE GROUP AG', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1010690', N'L''OCCITANE(FAR EAST) LTD.', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011463', N'LVMH Fragrances and Cosmetics', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011381', N'POLA COSMETICS (THAILAND) CO.,LTD', N'THB', N'D60I', N'PAYLOCAL 60 DAYS FROM INVOICE DATE', N'201', N'T/T Normal Pay local', N'DDP', 1),
        (N'1010575', N'Sisley Horizons Pte. Ltd.', N'THB', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'FCA', 1),
        (N'1010418', N'PROCTER & GAMBLE INTERNATIONAL', N'USD', N'C45I', N'CREDIT 45 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'DAP', 1),
        (N'1011173', N'INTER PARFUMS USD, LLC', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'DAT', 1),
        (N'1011427', N'Acqua di Parma SRL', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1010376', N'PUIG INTERNATIONAL, S.A.', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1010556', N'INTER PARFUMS', N'USD', N'C90I', N'CREDIT 90 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1010084', N'BEAUTE PRESTIGE INTERNATIONAL', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'FOB', 1),
        (N'1011541', N'Rituals Cosmetics Hong Kong Ltd.', N'USD', N'C60C', N'CREDIT 60 DAYS FROM B/L DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1010557', N'EUROITALIA SRL', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1011378', N'DIPTYQUE PARIS', N'EUR', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011559', N'Parfum Francis Kurkdjian', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1011421', N'ESTEE LAUDER AG LACHEN', N'USD', N'C60I', N'CREDIT 60 DAYS FROM INVOICE DATE', N'200', N'T/T Normal', N'CIP', 1),
        (N'1060047', N'AIM DHRAM CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1060046', N'MULTIPLY BY EIGHT CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', N'LOD', 1),
        (N'1021474', N'THAIAREE FOOD AND FRIENDS CO., LTD.', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020004', N'LIM JING HIENG FOODS CO.,LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020033', N'THAI NISHIKAWA INTERNATIONAL', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020030', N'PENCE MARKETING CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021725', N'BOON RAWD TRADING CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021773', N'SOPHA SRIJANTRA LIMITED PARTNERSHIP', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020422', N'MAE FAH LUANG FOUNDATION', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021987', N'Royal Chitralada Project', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1022088', N'Doi Kham Food Products Co., Ltd.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021586', N'CP CONSUMER PRODUCT CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1022217', N'THE BRITISH DISPENSARY (L.P.)', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021270', N'UNILEVER THAI TRADING COMPANY', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1020781', N'DKSH (THAILAND) LIMITED', N'THB', N'C90E', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021177', N'DIETHELM KELLER LOGISTICS LTD.', N'THB', N'C90E', N'CREDIT 90 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021503', N'HATAKABB (SIM TIEN HOR) CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021787', N'NIDA PHARMA INCORPORATION CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021802', N'TNP HEALTH CARE CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021833', N'FIVE PAGODAS PHARMACY CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021840', N'MONTANA MARKETING COMPANY LIMITED', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021871', N'HATAKABB TRADING (THAILAND)', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021913', N'THAI HERBAL HONGTHAI CO., LTD', N'THB', N'C60E', N'CREDIT 60 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021963', N'DEVAKAM APOTHECARY HALL CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021571', N'SYNNEX (THAILAND) PUBLIC CO., LTD.', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021654', N'PHILIPS (THAILAND) LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020769', N'SiS Distribution (Thailand) Public', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020767', N'RTB TECHNOLOGY CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021443', N'A.E.C. 2015 (THAILAND) CO., LTD.', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1022346', N'Apichaya  Layongkanon', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021879', N'NARASAMUT CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021785', N'NITHEE SUTHAMMARUK', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021863', N'NUTCHARATH  CHUMPANICHWASUT', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021325', N'PANNEE THONGSUK', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021439', N'RAVEEWAN KHANADNID', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021797', N'ROONGNAPA CHAIDEE', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021345', N'TROPICANA OIL CO.,LTD.', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1011139', N'CENTAUR TRAVEL RETAIL ASIA LTD.', N'USD', N'C60B', N'CREDIT 60 DAYS FROM AWB DATE', N'200', N'T/T Normal', N'CIF', 1),
        (N'1022019', N'FOREO (THAILAND) LTD', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'200', N'T/T Normal', NULL, 1),
        (N'1021835', N'AROMDIN COMPANY LIMITED', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1022128', N'THAINAMTHIP CORPORATION LIMITED', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1060039', N'V&A Holding Co.,Ltd', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020019', N'SINO PACIFIC TRADING (THAILAND)', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020755', N'Saijaithai Foundation under The', N'THB', N'C90D', N'CREDIT 90 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020770', N'ROYAL PROJECT FOUNDATION-', N'THB', N'C15D', N'CREDIT 15 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020771', N'ROYAL PROJECT FOUNDATION', N'THB', N'C15D', N'CREDIT 15 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021940', N'SUVARNACHAD COMPANY LIMITED', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1020024', N'United Leather Product co.,ltd.', N'THB', N'C12D', N'CREDIT 120 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021878', N'KAMNUANKARN CO., LTD.', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021353', N'EKAWAT INDRACHAI', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021266', N'POP THEPHASIT', N'THB', N'C60D', N'CREDIT 60 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021430', N'TEERAYUTH KHAMPHUN', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021390', N'CHUMPORN SUTHIBOON', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021347', N'CHASADA HONGSUCHON', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021697', N'NATAMON SANANTUNG', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021592', N'KITTIPHAN  SUTTISA', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021323', N'WANPEN SAENGKANHA', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021383', N'NINE PHETCHABUN TRADING CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021365', N'KNIGHT BLACK HORSE WINERY CO.,LTD.', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', N'LOD', 1),
        (N'1021441', N'CHARTREE NOISOPA', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021360', N'PRONPUN WIWITTHAKHUN', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1022067', N'RATTIYA  KLAMBOON', N'THB', N'C45D', N'CREDIT 45 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021573', N'Ruean Samut Community Enterprise', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021598', N'CHAI  JITTAWIMOL', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021689', N'LINDA SUWANNATAI', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021326', N'SOMPRASONG PAPOPAN', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021732', N'SUMAMAL TEJA', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021440', N'CHANANYA DONKUEANSOM', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021336', N'PITCHAYAPORN MEETAESUP', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021337', N'GOLD CROSS COMPANY LIMITED', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021338', N'SARUT PRAKATKIT', N'THB', N'C15E', N'CREDIT 15 DAYS FROM DELIVERY DATE', N'300', N'Local', N'LOD', 1),
        (N'1021485', N'PHONGCHAYUTH  PHONATHA', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021574', N'SUTHANYA  SEETASAN', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021397', N'SUCHADA LAVITRANGSIMA', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021741', N'TANYALUK THAWIKITTIPHAN', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021342', N'SANTI KUEAYU', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021352', N'PEERASUK HNOOPHET', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021367', N'SUPHIN NAHUAL', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021433', N'LAOR AATWICHAI', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021633', N'UMMORN YAEMSRI', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021348', N'SIRIWAN REANTHONGCHAI', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1022050', N'SUKSAN KUMNODNAA', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021320', N'PAWINEE BOONARSA', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021374', N'BAAN THANYATHIP ORGANIC & HEALTHY', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021795', N'Nature Life Herb', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021464', N'SINGHA  POUNGOUR', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021346', N'MInd & Body by Ms. Budsakorn', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021707', N'ANEKPONG PATSAKHAM', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021343', N'POOKL OHN COUNTRY CLUB LTD., PART.', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021361', N'Surat Jirarattanawong', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021748', N'CHANYAPHAT TANGKLANG', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021888', N'SATTABONGKOT TRA BUADAENG CO., LTD.', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021366', N'KITTIMA PANDARA', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021715', N'ANONG BURAVONG', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021547', N'S.T.I. MARKETING (1995) CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021484', N'PATSACHAD  SUDTAJIRAD', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021344', N'CH-SIKARIN LTD.,PART.', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1022162', N'THAWEEPHAN  PRODUCT LIMITED', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021339', N'KREANGKRAI NAKSAWASDI', N'THB', N'C15E', N'CREDIT 15 DAYS FROM DELIVERY DATE', N'300', N'Local', N'LOD', 1),
        (N'1021536', N'PRACH  NIYOMKAR', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021335', N'KITTI PHOPPRASERT', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1021860', N'PLEONTA THAI SNACK CO.,LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1021331', N'SAMER PROMWONGSA', N'THB', N'C30E', N'CREDIT 30 DAYS FROM DELIVERY DATE', N'300', N'Local', NULL, 1),
        (N'1011428', N'Bulgari South Asian Operations', N'SGD', N'C30N', N'CREDIT 30 DAYS END OF MONTH OF INVOICE DATE', N'200', N'T/T Normal', N'DAP', 1),
        (N'1021225', N'MENTAGRAM CO., LTD.', N'THB', N'C30D', N'CREDIT 30 DAYS FROM BILLING DATE', N'300', N'Local', NULL, 1),
        (N'1011577', N'LE SPORTSAC, INC.', N'USD', N'C980', N'15 DAYS AFTER WEEKLY SALES PERIOD', N'200', N'T/T Normal', N'DDP', 1),
        (N'OTB-AP-01', N'DUMMY', NULL, NULL, NULL, N'200', N'T/T Normal', NULL, 1),
        (N'OTB-AP-01', N'DUMMY', NULL, NULL, NULL, N'300', N'Local', NULL, 1)
) AS S (VendorCode, Vendor, CCY, PaymentTermCode, PaymentTerm, SegmentCode, Segment, Incoterm, isActive)
ON T.VendorCode = S.VendorCode AND ISNULL(T.SegmentCode, N'') = ISNULL(S.SegmentCode, N'')
WHEN MATCHED THEN
    UPDATE SET
        T.Vendor = S.Vendor, T.CCY = S.CCY, T.PaymentTermCode = S.PaymentTermCode, T.PaymentTerm = S.PaymentTerm, T.Segment = S.Segment, T.Incoterm = S.Incoterm, T.isActive = S.isActive
WHEN NOT MATCHED BY TARGET THEN
    INSERT (VendorCode, Vendor, CCY, PaymentTermCode, PaymentTerm, SegmentCode, Segment, Incoterm, isActive)
    VALUES (S.VendorCode, S.Vendor, S.CCY, S.PaymentTermCode, S.PaymentTerm, S.SegmentCode, S.Segment, S.Incoterm, S.isActive);
GO

MERGE dbo.MS_User AS T
USING
(
    VALUES
        (1, N'methee.treewichian@kingpower.com', N'Methee Treewichian', N'methee.treewichian@kingpower.com', 1, CAST('2026-01-23 17:53:44' AS datetime2(0)), CAST('2025-11-28 14:46:32' AS datetime2(0))),
        (2, N'arunrung_t@kingpower.com', N'Arunrung Tantrakul', N'arunrung_t@kingpower.com', 1, CAST('2026-01-26 13:58:02' AS datetime2(0)), CAST('2025-11-28 17:54:27' AS datetime2(0))),
        (3, N'chatsiri_p@kingpower.com', N'Chatsiri Prathuangpokjaroen', N'chatsiri_p@kingpower.com', 1, CAST('2026-01-23 10:40:04' AS datetime2(0)), CAST('2025-11-28 17:54:54' AS datetime2(0))),
        (4, N'nachanok_j@kingpower.com', N'Nachanok Jaroonwetchakul', N'nachanok_j@kingpower.com', 1, CAST('2026-01-26 13:51:27' AS datetime2(0)), CAST('2025-11-28 18:05:11' AS datetime2(0))),
        (5, N'phenpat.aree@kingpower.com', N'Phenpat Aree', N'phenpat.aree@kingpower.com', 1, CAST('2026-01-23 16:19:13' AS datetime2(0)), CAST('2025-11-28 20:59:00' AS datetime2(0))),
        (6, N'wichai_k@kingpower.com', N'Wichai Kasemsongporn', N'wichai_k@kingpower.com', 1, CAST('2026-01-22 10:09:56' AS datetime2(0)), CAST('2025-12-16 17:17:08' AS datetime2(0))),
        (7, N'angsana_b@kingpower.com', N'Angsana Butsa', N'angsana_b@kingpower.com', 1, CAST('2026-01-22 10:51:24' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (8, N'anonglak.wanawiwit@kingpower.com', NULL, NULL, 1, CAST('2026-01-26 10:21:31' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (9, N'araya_p@kingpower.com', N'Miss Araya Plengkham', N'araya_p@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (10, N'aree_t@kingpower.com', N'Aree Tepsing', N'aree_t@kingpower.com', 1, CAST('2026-01-23 15:16:58' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (11, N'arunotai.inparam@kingpower.com', N'Miss Arunotai Inparam', N'arunotai.inparam@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (12, N'attapon_j@kingpower.com', N'Attapon Jiworrapong', N'attapon_j@kingpower.com', 1, CAST('2026-01-26 10:00:14' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (13, N'bhubesh_p@kingpower.com', N'Bhubesh Punyasawangchitra', N'bhubesh_p@kingpower.com', 1, CAST('2026-01-22 10:48:57' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (14, N'chaiwat_c@kingpower.com', N'Mr. Chaiwat Chanchuchchawarn', N'chaiwat_c@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (15, N'chalita.charoensupanimit@kingpower.com', N'Miss Chalita Charoensupanimit', N'chalita.charoensupanimit@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (16, N'charnyut_d@kingpower.com', N'Mr. Charnyut Dumnernsawat', N'charnyut_d@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (17, N'chayawat.thongkrua@kingpower.com', N'Mr. Chayawat Thongkrua', N'chayawat.thongkrua@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (18, N'chidchanok_t@kingpower.com', N'Miss Chidchanok Tantiyawarong', N'chidchanok_t@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (19, N'daranee_k@kingpower.com', N'Daranee Kasiwat', N'daranee_k@kingpower.com', 1, CAST('2026-01-22 10:50:59' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (20, N'dokor_r@kingpower.com', N'Miss Dok-or Rueangbut', N'dokor_r@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (21, N'duangphan_d@kingpower.com', N'Miss Duangphan Dechpreecha', N'duangphan_d@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (22, N'ek-poranee.youngtrong@kingpower.com', N'Miss Ek-poranee Youngtrong', N'ek-poranee.youngtrong@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (23, N'jananya_v@kingpower.com', N'Mrs. Jananya Virunanond', N'jananya_v@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (24, N'jirapannee_c@kingpower.com', N'Jirapannee Charungchitcharoen', N'jirapannee_c@kingpower.com', 1, CAST('2026-01-22 10:49:25' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (25, N'jiraporn_p@kingpower.com', N'Jiraporn Panyuag', N'jiraporn_p@kingpower.com', 1, CAST('2026-01-22 10:54:28' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (26, N'jirawan_ph@kingpower.com', N'Jirawan Phrommetta', N'jirawan_ph@kingpower.com', 1, CAST('2026-01-22 14:59:15' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (27, N'jiraya.chinakarn@kingpower.com', N'Jiraya Chinakarn', N'jiraya.chinakarn@kingpower.com', 1, CAST('2026-01-22 10:27:41' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (28, N'jitpanna_m@kingpower.com', N'Miss Jitpanna Mungkarnngan', N'jitpanna_m@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (29, N'jitsupa.wangcherdchai@kingpower.com', N'Jitsupa Wangcherdchai', N'jitsupa.wangcherdchai@kingpower.com', 1, CAST('2026-01-22 14:59:53' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (30, N'kamonnan.srivichai@kingpower.com', N'Miss Kamonnan Srivichai', N'kamonnan.srivichai@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (31, N'kanvara.jivacharoenchai@kingpower.com', N'Miss Kanvara Jivacharoenchai', N'kanvara.jivacharoenchai@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (32, N'kanvara.norakim@kingpower.com', N'Miss Kanvara Norakim', N'kanvara.norakim@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (33, N'kanyarat.thanatwatcharanon@kingpower.com', N'Kanyarat Thanatwatcharanon', N'kanyarat.thanatwatcharanon@kingpower.com', 1, CAST('2026-01-20 14:18:56' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (34, N'korawitch.wanganansukdee@kingpower.com', N'Mr. Korawitch Wanganansukdee', N'korawitch.wanganansukdee@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (35, N'kornrawee_n@kingpower.com', N'Kornrawee Nititham', N'kornrawee_n@kingpower.com', 1, CAST('2026-01-22 09:56:23' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (36, N'kullaporn.suwanpimolkul@kingpower.com', N'Kullaporn Suwanpimolkul', N'kullaporn.suwanpimolkul@kingpower.com', 1, CAST('2026-01-22 10:59:33' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (37, N'maneepun@kingpower.com', N'Mrs. Maneephan Charuchinda', N'maneepun@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (38, N'marleerat_p@kingpower.com', N'Miss Marleerat Patjareesakul', N'marleerat_p@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (39, N'mayuree.reangkesa@kingpower.com', N'Mayuree reangkesa', N'mayuree.reangkesa@kingpower.com', 1, CAST('2026-01-23 16:40:07' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (40, N'nalinee.suksawaeng@kingpower.com', N'Nalinee Suksawaeng', N'nalinee.suksawaeng@kingpower.com', 1, CAST('2026-01-22 10:49:44' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (41, N'napaporn_h@kingpower.com', N'Miss Napaporn Henwongprasert', N'napaporn_h@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (42, N'natchaya.angsuwarangsi@kingpower.com', N'Natchaya Angsuwarangsi', N'natchaya.angsuwarangsi@kingpower.com', 1, CAST('2026-01-22 16:57:20' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (43, N'nattakarn_s@kingpower.com', N'Nattakran Sujitgom', N'nattakarn_s@kingpower.com', 1, CAST('2026-01-22 11:02:27' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (44, N'nattaporn_t@kingpower.com', N'Miss Nattaporn Teerapaisantanakorn', N'nattaporn_t@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (45, N'nawamon.sirivarothakul@kingpower.com', NULL, NULL, 1, CAST('2026-01-22 17:20:40' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (46, N'nurawee_w@kingpower.com', N'Miss Nurawee Wongchaisuwan', N'nurawee_w@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (47, N'orathai_w@kingpower.com', N'Miss Orathai Waroros', N'orathai_w@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (48, N'ornuma_p@kingpower.com', N'Miss Orn-uma Puthipotchana', N'ornuma_p@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (49, N'panatda.boontananit@kingpower.com', N'Miss Panatda Boontananit', N'panatda.boontananit@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (50, N'panyalux_p@kingpower.com', N'Panyalux Promadej', N'panyalux_p@kingpower.com', 1, CAST('2026-01-16 18:23:31' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (51, N'parasorn.pattanasakullert@kingpower.com', N'Parasorn Pattanasakullert', N'parasorn.pattanasakullert@kingpower.com', 1, CAST('2026-01-26 10:37:18' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (52, N'patcharaporn_s@kingpower.com', N'Patcharaporn Sonthisaingam', N'patcharaporn_s@kingpower.com', 1, CAST('2026-01-23 19:21:06' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (53, N'patchaya_s@kingpower.com', N'Patchaya Sukanan', N'patchaya_s@kingpower.com', 1, CAST('2026-01-22 10:04:38' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (54, N'pawan.supradit@kingpower.com', N'Miss Pawan Supradit', N'pawan.supradit@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (55, N'pawinee_p@kingpower.com', N'Pawinee Wachirabenjapong', N'pawinee_p@kingpower.com', 1, CAST('2026-01-22 10:49:30' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (56, N'phakpoom_s@kingpower.com', N'Mr. Phakpoom Suthavart', N'phakpoom_s@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (57, N'pilaiporn_p@kingpower.com', N'Pilaiporn Pannasakpanich', N'pilaiporn_p@kingpower.com', 1, CAST('2026-01-22 10:49:55' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (58, N'pimlada_t@kingpower.com', N'Miss Pimlada Tanasathitwong', N'pimlada_t@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (59, N'pimsuda.rojanapiensatith@kingpower.com', N'Miss Pimsuda Rojanapiensatith', N'pimsuda.rojanapiensatith@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (60, N'pongpanot.thanomngam@kingpower.com', N'Pongpanot Thanomngam', N'pongpanot.thanomngam@kingpower.com', 1, CAST('2026-01-23 19:21:03' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (61, N'prachya_s@kingpower.com', N'Prachya Suksonthi', N'prachya_s@kingpower.com', 1, CAST('2026-01-22 11:08:25' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (62, N'punyanuch.manuthad@kingpower.com', N'Punyanuch Manuthad', N'punyanuch.manuthad@kingpower.com', 1, CAST('2026-01-22 10:49:34' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (63, N'raelene.johnson@kingpower.com', N'Mrs. Raelene Dawn Johnson', N'raelene.johnson@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (64, N'ramon.chuichai@kingpower.com', N'Miss Ramon Chuichai', N'ramon.chuichai@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (65, N'salin.sae-ung@kingpower.com', N'Salin Sae Ung', N'salin.sae-ung@kingpower.com', 1, CAST('2026-01-22 10:49:32' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (66, N'salutaya.anantachai@kingpower.com', N'Miss Salutaya Anantachai', N'salutaya.anantachai@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (67, N'saowanee_k@kingpower.com', N'Saowanee Kokeluecha', N'saowanee_k@kingpower.com', 1, CAST('2026-01-22 10:50:31' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (68, N'saralee_w@kingpower.com', N'Miss Saralee Wongsakvanich', N'saralee_w@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (69, N'satima_p@kingpower.com', N'Miss Satima Phoomsiri', N'satima_p@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (70, N'sirikarn.srisuwanaporn@kingpower.com', N'Miss Sirikarn Srisuwanaporn', N'sirikarn.srisuwanaporn@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (71, N'siritorn.saktaweewong@kingpower.com', N'Siritorn Saktaweewong', N'siritorn.saktaweewong@kingpower.com', 1, CAST('2026-01-22 10:49:30' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (72, N'soontaree.prasopsomboon@kingpower.com', N'Soontaree Prasopsomboon', N'soontaree.prasopsomboon@kingpower.com', 1, CAST('2026-01-22 11:18:30' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (73, N'suchitra_k@kingpower.com', N'Suchitra Kaewthongmool', N'suchitra_k@kingpower.com', 1, CAST('2026-01-22 10:49:23' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (74, N'sunsanee_s@kingpower.com', N'Sunsanee Sitawarin', N'sunsanee_s@kingpower.com', 1, CAST('2026-01-22 10:56:20' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (75, N'supitcha.la-ongchan@kingpower.com', N'Miss Supitcha La-ongchan', N'supitcha.la-ongchan@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (76, N'sureeporn_p@kingpower.com', N'Miss Sureeporn Phun-im', N'sureeporn_p@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (77, N'suttinee.onsunthia@kingpower.com', N'Miss Suttinee Onsunthia', N'suttinee.onsunthia@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (78, N'suttipong.puttikaew@kingpower.com', N'Mr. Suttipong Puttikaew', N'suttipong.puttikaew@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (79, N'thanawat.auttra@kingpower.com', N'Mr. Thanawat Auttra', N'thanawat.auttra@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (80, N'tharin.savettanan@kingpower.com', N'Mrs. Tharin Savettanan', N'tharin.savettanan@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (81, N'theejutha.sudjaijam@kingpower.com', N'Miss Theejutha Sudjaijam', N'theejutha.sudjaijam@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (82, N'thitiworada_a@kingpower.com', N'Miss Thitiworada Aukpawan', N'thitiworada_a@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (83, N'tuangporn_p@kingpower.com', N'Miss Tuangporn Pongnuch', N'tuangporn_p@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (84, N'ulas.tekin@kingpower.com', N'Mr. Ulas Tekin', N'ulas.tekin@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (85, N'varut_s@kingpower.com', N'Varut Sirichantaradilok', N'varut_s@kingpower.com', 1, CAST('2026-01-22 10:49:23' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (86, N'vitoon_v@kingpower.com', N'Mr. Vitoon Visarnsompong', N'vitoon_v@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (87, N'wanlaya_c@kingpower.com', N'Miss Wanlaya Chansaengsri', N'wanlaya_c@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (88, N'wannee_c@kingpower.com', N'Miss Wannee Chudkratok', N'wannee_c@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (89, N'wantanee_c@kingpower.com', N'Miss Wantanee Charoenkrajang', N'wantanee_c@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (90, N'warangkana.nilkamhaeng@kingpower.com', N'Mrs. Warangkana Nilkamhaeng', N'warangkana.nilkamhaeng@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (91, N'waratchaya.pattarawilaiwit@kingpower.com', N'Miss Waratchaya Pattarawilaiwit', N'waratchaya.pattarawilaiwit@kingpower.com', 1, NULL, CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (92, N'wilawan_c@kingpower.com', N'Wilawan Chantaraprasith', N'wilawan_c@kingpower.com', 1, CAST('2026-01-22 10:03:45' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (93, N'wimonnatcha.chivapornthip@kingpower.com', NULL, NULL, 1, CAST('2026-01-23 13:54:31' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (94, N'wiphaporn.parkpleenok@kingpower.com', N'Wiphaporn Parkpleenok', N'wiphaporn.parkpleenok@kingpower.com', 1, CAST('2026-01-22 10:49:41' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (95, N'yongsak_k@kingpower.com', N'Yongsak Kongthanarat', N'yongsak_k@kingpower.com', 1, CAST('2026-01-23 11:06:56' AS datetime2(0)), CAST('2025-12-17 17:32:50' AS datetime2(0))),
        (96, N'wanvimol_l@kingpower.com', N'Wanvimol Likitdechasak', N'wanvimol_l@kingpower.com', 1, CAST('2026-01-22 10:50:12' AS datetime2(0)), CAST('2026-01-22 10:49:40' AS datetime2(0))),
        (97, N'kasinee_p@kingpower.com', N'Kasinee Pisawongnarong', N'kasinee_p@kingpower.com', 1, CAST('2026-01-22 11:03:49' AS datetime2(0)), CAST('2026-01-22 11:03:49' AS datetime2(0)))
) AS S (UserID, Username, FullName, Email, IsActive, LastLoginDate, CreateDate)
ON T.UserID = S.UserID
WHEN MATCHED THEN
    UPDATE SET
        T.Username = S.Username, T.FullName = S.FullName, T.Email = S.Email, T.IsActive = S.IsActive, T.LastLoginDate = S.LastLoginDate, T.CreateDate = S.CreateDate
WHEN NOT MATCHED BY TARGET THEN
    INSERT (UserID, Username, FullName, Email, IsActive, LastLoginDate, CreateDate)
    VALUES (S.UserID, S.Username, S.FullName, S.Email, S.IsActive, S.LastLoginDate, S.CreateDate);
GO

MERGE dbo.MS_Role AS T
USING
(
    VALUES
        (1, N'Admin', N'ผู้ดูแลระบบสูงสุด'),
        (2, N'Buyer', N'ทีม MD'),
        (3, N'MBC', N'ทีมMBC')
) AS S (RoleID, RoleName, Description)
ON T.RoleID = S.RoleID
WHEN MATCHED THEN
    UPDATE SET
        T.RoleName = S.RoleName, T.Description = S.Description
WHEN NOT MATCHED BY TARGET THEN
    INSERT (RoleID, RoleName, Description)
    VALUES (S.RoleID, S.RoleName, S.Description);
GO

MERGE dbo.Map_User_Role AS T
USING
(
    VALUES
        (1, 1, 1),
        (2, 2, 3),
        (3, 3, 3),
        (4, 4, 3),
        (5, 5, 1),
        (7, 6, 2),
        (8, 7, 2),
        (9, 8, 2),
        (10, 9, 2),
        (11, 10, 2),
        (12, 11, 2),
        (13, 12, 2),
        (14, 13, 2),
        (15, 14, 2),
        (16, 15, 2),
        (17, 16, 2),
        (18, 17, 2),
        (19, 18, 2),
        (20, 19, 2),
        (21, 20, 2),
        (22, 21, 2),
        (23, 22, 2),
        (24, 23, 2),
        (25, 24, 2),
        (26, 25, 2),
        (27, 26, 2),
        (28, 27, 2),
        (29, 28, 2),
        (30, 29, 2),
        (31, 30, 2),
        (32, 31, 2),
        (33, 32, 2),
        (34, 33, 2),
        (35, 34, 2),
        (36, 35, 2),
        (37, 36, 2),
        (38, 37, 2),
        (39, 38, 2),
        (40, 39, 2),
        (41, 40, 2),
        (42, 41, 2),
        (43, 42, 2),
        (44, 43, 2),
        (45, 44, 2),
        (46, 45, 2),
        (47, 46, 2),
        (48, 47, 2),
        (49, 48, 2),
        (50, 49, 2),
        (51, 50, 2),
        (52, 51, 2),
        (53, 52, 2),
        (54, 53, 2),
        (55, 54, 2),
        (56, 55, 2),
        (57, 56, 2),
        (58, 57, 2),
        (59, 58, 2),
        (60, 59, 2),
        (61, 60, 2),
        (62, 61, 2),
        (63, 62, 2),
        (64, 63, 2),
        (65, 64, 2),
        (66, 65, 2),
        (67, 66, 2),
        (68, 67, 2),
        (69, 68, 2),
        (70, 69, 2),
        (71, 70, 2),
        (72, 71, 2),
        (73, 72, 2),
        (74, 73, 2),
        (75, 74, 2),
        (76, 75, 2),
        (77, 76, 2),
        (78, 77, 2),
        (79, 78, 2),
        (80, 79, 2),
        (81, 80, 2),
        (82, 81, 2),
        (83, 82, 2),
        (84, 83, 2),
        (85, 84, 2),
        (86, 85, 2),
        (87, 86, 2),
        (88, 87, 2),
        (89, 88, 2),
        (90, 89, 2),
        (91, 90, 2),
        (92, 91, 2),
        (93, 92, 2),
        (94, 93, 2),
        (95, 94, 2),
        (96, 95, 2)
) AS S (MapID, UserID, RoleID)
ON T.MapID = S.MapID
WHEN MATCHED THEN
    UPDATE SET
        T.UserID = S.UserID, T.RoleID = S.RoleID
WHEN NOT MATCHED BY TARGET THEN
    INSERT (MapID, UserID, RoleID)
    VALUES (S.MapID, S.UserID, S.RoleID);
GO

MERGE dbo.Map_Role_Permission AS T
USING
(
    VALUES
        (1, 1, 1, 1, 1, 1, 1),
        (2, 1, 2, 1, 1, 1, 1),
        (3, 1, 3, 1, 1, 1, 1),
        (4, 1, 4, 1, 1, 1, 1),
        (5, 1, 5, 1, 1, 1, 1),
        (6, 1, 6, 1, 1, 1, 1),
        (7, 1, 7, 1, 1, 1, 1),
        (8, 1, 8, 1, 1, 1, 1),
        (9, 1, 9, 1, 1, 1, 1),
        (10, 1, 10, 1, 1, 1, 1),
        (11, 1, 11, 1, 1, 1, 1),
        (12, 1, 12, 1, 1, 1, 1),
        (13, 1, 13, 1, 1, 1, 1),
        (14, 3, 4, 1, 1, 0, 1),
        (15, 2, 12, 1, 0, 0, 0),
        (16, 3, 1, 1, 1, 1, 1),
        (17, 3, 2, 1, 1, 1, 1),
        (18, 3, 3, 1, 1, 1, 1),
        (19, 3, 5, 1, 1, 1, 1),
        (20, 3, 6, 1, 1, 1, 1),
        (21, 3, 7, 1, 1, 1, 1),
        (22, 3, 8, 1, 1, 1, 1),
        (23, 3, 9, 1, 1, 1, 1),
        (24, 3, 10, 1, 1, 1, 1),
        (25, 3, 11, 1, 1, 1, 1),
        (26, 3, 12, 1, 1, 1, 1),
        (27, 3, 13, 1, 1, 1, 1),
        (28, 2, 3, 1, 0, 0, 0),
        (29, 2, 7, 1, 0, 0, 0),
        (30, 2, 5, 1, 0, 0, 0)
) AS S (PermissionID, RoleID, MenuID, CanView, CanEdit, CanDelete, CanApprove)
ON T.PermissionID = S.PermissionID
WHEN MATCHED THEN
    UPDATE SET
        T.RoleID = S.RoleID, T.MenuID = S.MenuID, T.CanView = S.CanView, T.CanEdit = S.CanEdit, T.CanDelete = S.CanDelete, T.CanApprove = S.CanApprove
WHEN NOT MATCHED BY TARGET THEN
    INSERT (PermissionID, RoleID, MenuID, CanView, CanEdit, CanDelete, CanApprove)
    VALUES (S.PermissionID, S.RoleID, S.MenuID, S.CanView, S.CanEdit, S.CanDelete, S.CanApprove);
GO

PRINT N'Master data seed generated from Excel completed.';
GO
